apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: guardian-service
  name: guardian-service
spec:
  ports:
    - name: "5007"
      port: 5007
      targetPort: 5007
    - name: "6555"
      port: 6555
      targetPort: 6555
  selector:
    io.kompose.service: guardian-service
status:
  loadBalancer: {}
