apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: ipfs-node
  name: ipfs-node
spec:
  ports:
    - name: "5001"
      port: 5001
      targetPort: 5001
    - name: "5002"
      port: 5002
      targetPort: 5002
    - name: "4001"
      port: 4001
      targetPort: 4001
    - name: "4002"
      port: 4002
      targetPort: 4002
    - name: "8080"
      port: 8080
      targetPort: 8080
    - name: "8081"
      port: 8081
      targetPort: 8081
  selector:
    io.kompose.service: ipfs-node
status:
  loadBalancer: {}
