apiVersion: v1
kind: Service
metadata:
  annotations:
    
    kompose.version: 1.28.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: policy-service
  name: policy-service
spec:
  ports:
    - name: "5006"
      port: 5006
      targetPort: 5006
  selector:
    io.kompose.service: policy-service
status:
  loadBalancer: {}
