apiVersion: v1
kind: Service
metadata:
  annotations:
    
    kompose.version: 1.28.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: worker-service-1
  name: worker-service-1
spec:
  ports:
    - name: "6555"
      port: 6555
      targetPort: 6555
  selector:
    io.kompose.service: worker-service-1
status:
  loadBalancer: {}
