apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    
    kompose.version: 1.28.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: mrv-sender
  name: mrv-sender
spec:
  replicas: 2
  selector:
    matchLabels:
      io.kompose.service: mrv-sender
  strategy: {}
  template:
    metadata:
      annotations:
        
        kompose.version: 1.28.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/guardian-default: "true"
        io.kompose.service: mrv-sender
    spec:
      containers:
        - image: gcr.io/hedera-registry/mrv-sender
          name: mrv-sender
          ports:
            - containerPort: 3003
            - containerPort: 5008
          resources: {}
      restartPolicy: Always
status: {}
