/**
 * Message action
 */
export enum MessageAction {
    CreateDID = 'create-did-document',
    CreateVC = 'create-vc-document',
    CreatePolicy = 'create-policy',
    PublishPolicy = 'publish-policy',
    DeletePolicy = 'delete-policy',
    CreateSchema = 'create-schema',
    PublishSchema = 'publish-schema',
    PublishSchemas = 'publish-schemas',
    DeleteSchema = 'delete-schema',
    CreateTopic = 'create-topic',
    CreateVP = 'create-vp-document',
    PublishSystemSchema = 'publish-system-schema',
    PublishSystemSchemas = 'publish-system-schemas',
    Init = 'Init',
    ChangeMessageStatus = 'change-message-status',
    RevokeDocument = 'revoke-document',
    DeleteDocument = 'delete-document',
    UseToken = 'token-issue',
    CreateToken = 'create-token',
    CreateMultiPolicy = 'create-multi-policy',
    Mint = 'mint',
    PublishModule = 'publish-module',
    PublishTag = 'publish-tag',
    DeleteTag = 'delete-tag',
    PublishTool = 'publish-tool',
    CreateTool = 'create-tool',
    CreateContract = 'create-contract',
    DiscontinuePolicy = 'discontinue-policy',
    DeferredDiscontinuePolicy = 'deferred-discontinue-policy',
    MigrateVC = 'migrate-vc-document',
    MigrateVP = 'migrate-vp-document',
    CreateRole = 'create-role',
    UpdateRole = 'update-role',
    DeleteRole = 'delete-role',
    SetRole = 'set-role',
    PublishPolicyStatistic = 'publish-policy-statistic',
    CreateStatisticAssessment = 'create-assessment-document',
    PublishPolicyLabel = 'publish-policy-label',
    CreateLabelDocument = 'create-label-document',
    PublishFormula = 'publish-formula',
    CreateComment = 'create-policy-comment',
    CreateDiscussion = 'create-policy-discussion',
}
