import { BlockType } from '@guardian/interfaces';
import { PolicyTool } from '../../entity/index.js';
import { XlsxSchema } from './xlsx-schema.js';

export class TagIndexer {
    private index: number;

    constructor() {
        this.index = Date.now();
    }

    public getTag(type: BlockType, data: XlsxSchema | PolicyTool): string {
        if (type === BlockType.Tool) {
            return `Tool_${++this.index}`;
        }
        if (type === BlockType.Container) {
            if (data) {
                const name = (data.name).slice(0, 20).replace(/ /ig, '_');
                return `${name}_Schema_Holder_${++this.index}`;
            } else {
                return `Root_Holder_${++this.index}`;
            }
        }
        if (type === BlockType.Request) {
            return `Schema_Entry_${++this.index}`;
        }
        if (type === BlockType.CustomLogicBlock) {
            return `Schema_Calculations_${++this.index}`;
        }
        return `Autogenerated_${++this.index}`;
    }
}
