export const REQUIRED_PROPS = {
    _ID: '_id',
    UUID: 'uuid',
    NAME: 'name',
    DESCRIPTION: 'description',
    STATUS: 'status',
    TOPIC_ID: 'topicId',
    INSTANCE_TOPIC_ID: 'instanceTopicId',
    VERSION: 'version',
    OWNER: 'owner',
    CREATOR: 'creator',
    MESSAGE_ID: 'messageId',
    DISCONTINUED_DATE: 'discontinuedDate',
    AVAILABILITY: 'availability',
    ORIGINAL_CHANGED: 'originalChanged'
};

export const UN_REQUIRED_PROPS = {
    CODE_VERSION: 'codeVersion',
    CREATE_DATE: 'createDate',
    CREATOR: 'creator',
    // DESCRIPTION: 'description',
    ID: 'id',
    // INSTANCE_TOPIC_ID: 'instanceTopicId',
    // NAME: 'name',
    OWNER: 'owner',
    POLICY_ROLES: 'policyRoles',
    POLICY_TAG: 'policyTag',
    // STATUS: 'status',
    TOOLS: 'tools',
    // TOPIC_ID: 'topicId',
    USER_GROUP: 'userGroup',
    USER_GROUPS: 'userGroups',
    USER_ROLE: 'userRole',
    USER_ROLES: 'userRoles',
    // UUID: 'uuid',
    // _ID: '_id',
};