export const PREFIXES = {
    ACCOUNTS: 'accounts',
    ARTIFACTS: '/artifacts/',
    MODULES: '/modules/',
    THEMES: '/themes/',
    SCHEMES: '/schemas/',
    TOOLS: '/tools/',
    TOOLS_MENU_ALL: '/tools/menu/all',
    POLICIES: '/policies/',
    CONTRACTS: '/contracts/',
    TAGS: '/tags/',
    IPFS: 'ipfs',
    PROFILES: 'profiles',
    POLICY_COMMENTS: '/policy-comments/',
};
