export const REQUIRED_PROPS = {
    ACTIVE: 'active',
    ENTITY: 'entity',
    NAME: 'name',
    OWNER: 'owner',
    SOURCE_VERSION: 'sourceVersion',
    STATUS: 'status',
    TOPIC_ID: 'topicId',
    _ID: '_id',
    CREATOR: 'creator',
    ERRORS: 'errors',
    VERSION: 'version',
    IRI: 'iri',
    UUID: 'uuid',
    MESSAGE_ID: 'messageId',
    DESCRIPTION: 'description',
};

export const UN_REQUIRED_PROPS = {
    DOCUMENT: 'document',
    // ACTIVE: 'active',
    CATEGORY: 'category',
    CODE_VERSION: 'codeVersion',
    CONTEXT: 'context',
    CONTEXT_FILE_ID: 'contextFileId',
    CONTEXT_URL: 'contextURL',
    CREATE_DATE: 'createDate',
    // CREATOR: 'creator',
    DEFS: 'defs',
    // DESCRIPTION: 'description',
    DOCUMENT_FILE_ID: 'documentFileId',
    DOCUMENT_URL: 'documentURL',
    // ENTITY: 'entity',
    // ERRORS: 'errors',
    HASH: 'hash',
    ID: 'id',
    // IRI: 'iri',
    IS_CREATOR: 'isCreator',
    IS_OWNER: 'isOwner',
    // MESSAGE_ID: 'messageId',
    // NAME: 'name',
    // OWNER: 'owner',
    READONLY: 'readonly',
    // SOURCE_VERSION: 'sourceVersion',
    // STATUS: 'status',
    SYSTEM: 'system',
    // TOPIC_ID: 'topicId',
    TOPIC_COUNT: 'topicCount',
    UPDATE_DATE: 'updateDate',
    // UUID: 'uuid',
    // VERSION: 'version',
    // _ID: '_id',
};
