export const REQUIRED_PROPS = {
    // CREATE_DATE: "createDate",
    // UPDATE_DATE: "updateDate",
    TOKEN_ID: 'tokenId',
    TOKEN: 'tokenName',
    TOKEN_SYMBOL: 'tokenSymbol',
    TOKEN_TYPE: 'tokenType',
    // DECIMALS: "decimals",
    // INITIAL_SUPPLY: "initialSupply",
    // ADMIN_ID: "adminId",
    // CHANGE_SUPPLY: "changeSupply",
    ENABLE_ADMIN: 'enableAdmin',
    // ENABLE_KYC: "enableKYC",
    // ENABLE_FREEZE: "enableFreeze",
    // ENABLE_WIPE: "enableWipe",
    // OWNER: "owner",
    // CREATOR: "creator",
    POLICY_ID: 'policyId',
    DRAFT_TOKEN: 'draftToken',
    // WIPE_CONTRACT_ID: "wipeContractId",
    _ID: '_id',
    // ID: "id",
};

export const UN_REQUIRED_PROPS = {
    CREATE_DATE: 'createDate',
    UPDATE_DATE: 'updateDate',
    TOKEN_ID: 'tokenId',
    TOKEN: 'tokenName',
    TOKEN_SYMBOL: 'tokenSymbol',
    TOKEN_TYPE: 'tokenType',
    DECIMALS: 'decimals',
    INITIAL_SUPPLY: 'initialSupply',
    ADMIN_ID: 'adminId',
    CHANGE_SUPPLY: 'changeSupply',
    ENABLE_ADMIN: 'enableAdmin',
    ENABLE_KYC: 'enableKYC',
    ENABLE_FREEZE: 'enableFreeze',
    ENABLE_WIPE: 'enableWipe',
    OWNER: 'owner',
    CREATOR: 'creator',
    POLICY_ID: 'policyId',
    DRAFT_TOKEN: 'draftToken',
    WIPE_CONTRACT_ID: 'wipeContractId',
    _ID: '_id',
    ID: 'id',
    // POLICIES: "policies",
    // POLICIES_IDS: "policyIds",
    // CAN_DELETE: "canDelete"
};