export const REQUIRED_PROPS = {
    DESCRIPTION: 'description',
    NAME: 'name',
    STATUS: 'status',
    TOPIC_ID: 'topicId',
    VERSION: 'version',
    MESSAGE_ID: 'messageId',
    _ID: '_id',
};

export const UN_REQUIRED_PROPS = {
    DOCUMENT: 'document',
    ACTIVE: 'active',
    CATEGORY: 'category',
    CODE_VERSION: 'codeVersion',
    CONTEXT: 'context',
    CONTEXT_FILE_ID: 'contextFileId',
    CONTEXT_URL: 'contextURL',
    CREATE_DATE: 'createDate',
    CREATOR: 'creator',
    DEFS: 'defs',
    // DESCRIPTION: 'description',
    DOCUMENT_FILE_ID: 'documentFileId',
    DOCUMENT_URL: 'documentURL',
    ENTITY: 'entity',
    ERRORS: 'errors',
    HASH: 'hash',
    ID: 'id',
    IRI: 'iri',
    IS_CREATOR: 'isCreator',
    IS_OWNER: 'isOwner',
    MESSAGE_ID: 'messageId',
    // NAME: 'name',
    OWNER: 'owner',
    READONLY: 'readonly',
    SOURCE_VERSION: 'sourceVersion',
    // STATUS: 'status',
    SYSTEM: 'system',
    // TOPIC_ID: 'topicId',
    UPDATE_DATE: 'updateDate',
    UUID: 'uuid',
    VERSION: 'version',
    // _ID: '_id',
};