import {
    CipherStrategy,
    bytesToUtf8,
    decryptWithKeyDerivedFromString,
    encryptWithKeyDerivedFromString,
    readArtifacts,
    utf8ToBytes,
    writeArtifacts,
} from '@utils/cryppo';
import fixtures from './cryppo.fixtures.json';

interface IVector {
    name: string;
    library: string;
    version: string;
    passphrase: string;
    plaintextEncoding: string;
    plaintext: string;
    serialized: string;
}

const vectors = fixtures.vectors as IVector[];

function base64ToBytes(value: string): Uint8Array {
    const binary = atob(value);
    const bytes = new Uint8Array(binary.length);
    for (let i = 0; i < binary.length; i++) {
        bytes[i] = binary.charCodeAt(i);
    }
    return bytes;
}

function plaintextOf(vector: IVector): Uint8Array {
    return vector.plaintextEncoding === 'utf8'
        ? utf8ToBytes(vector.plaintext)
        : base64ToBytes(vector.plaintext);
}

function sameBytes(actual: Uint8Array, expected: Uint8Array): boolean {
    if (actual.length !== expected.length) {
        return false;
    }
    return actual.every((byte, index) => byte === expected[index]);
}

describe('cryppo (@meeco/cryppo replacement)', () => {
    // The indexer is read-only, so decrypting payloads produced by the real library is the
    // behaviour that matters. These vectors were generated by @meeco/cryppo 2.0.2 and 3.0.2
    // before it was removed, and stand in for documents already published to Hedera and IPFS.
    // Running under Karma is what actually exercises WebCrypto in a browser.
    vectors.forEach((vector) => {
        it(`decrypts a ${vector.library}@${vector.version} payload (${vector.name})`, async () => {
            const decrypted = await decryptWithKeyDerivedFromString({
                serialized: vector.serialized,
                passphrase: vector.passphrase,
            });
            expect(decrypted).not.toBeNull();
            expect(sameBytes(decrypted as Uint8Array, plaintextOf(vector))).toBeTrue();
        });
    });

    it('decodes a legacy payload to the JSON the components expect', async () => {
        const vector = vectors.find((item) => item.name.startsWith('short-json')) as IVector;
        const decrypted = await decryptWithKeyDerivedFromString({
            serialized: vector.serialized,
            passphrase: vector.passphrase,
        });
        expect(JSON.parse(bytesToUtf8(decrypted as Uint8Array))).toEqual(
            JSON.parse(vector.plaintext)
        );
    });

    it('keeps the Aes256 prefix the components sniff for', async () => {
        vectors.forEach((vector) => expect(vector.serialized.startsWith('Aes256')).toBeTrue());

        const { serialized } = await encryptWithKeyDerivedFromString({
            passphrase: 'k',
            data: utf8ToBytes('payload'),
            strategy: CipherStrategy.AES_GCM,
        });
        expect(serialized.startsWith('Aes256')).toBeTrue();
        expect(serialized.split('.').length).toBe(5);
    });

    it('round-trips a document in the browser', async () => {
        const text = 'Привет 🌍 – naïve façade';
        const { serialized } = await encryptWithKeyDerivedFromString({
            passphrase: 'secret',
            data: utf8ToBytes(text),
            strategy: CipherStrategy.AES_GCM,
        });
        const decrypted = await decryptWithKeyDerivedFromString({
            serialized,
            passphrase: 'secret',
        });
        expect(bytesToUtf8(decrypted as Uint8Array)).toBe(text);
    });

    it('re-encodes artifacts byte for byte', () => {
        vectors.forEach((vector) => {
            const segments = vector.serialized.split('.');
            const artifacts = readArtifacts(segments[2], 'A');
            expect(
                writeArtifacts('A', [
                    ['iv', artifacts['iv']],
                    ['at', artifacts['at']],
                    ['ad', artifacts['ad']],
                ])
            ).toBe(segments[2]);
        });
    });

    it('rejects a wrong passphrase', async () => {
        await expectAsync(
            decryptWithKeyDerivedFromString({
                serialized: vectors[0].serialized,
                passphrase: 'wrong-passphrase',
            })
        ).toBeRejectedWithError(/Decryption failed/);
    });

    it('rejects the legacy YAML artifact format with an explicit error', async () => {
        const segments = vectors[0].serialized.split('.');
        segments[2] = btoa('---\niv: !binary |-\n  AAAA\n');
        await expectAsync(
            decryptWithKeyDerivedFromString({
                serialized: segments.join('.'),
                passphrase: vectors[0].passphrase,
            })
        ).toBeRejectedWithError(/Unsupported legacy cryppo serialization format/);
    });
});
