const CommonElements = {
	Input: "input",
    Div: "div",
    Button: "button",
    navBar: 'div[id = "navbar"]',
    administrationTab: 'Administration',
    mainPoliciesTab: 'Manage',
    policiesTab: 'Policies',
    userPoliciesTab: 'List of Policies',
    logsTab: 'Logs',
    settingsTab: 'Settings',
    statusTab: 'Status',
	dialogWindow: 'div[role="dialog"]',
    fileInput: 'input[type="file"]',
    Loading: "div.guardian-loading",
    userManagementTab: "User Management",
    checkBox: "p-checkbox",
    tokensTab: "Tokens & Contracts",
    listOfTokensTab:"List of Tokens",
    manageTokens:"Manage Tokens",
    svg: "svg-icon",
    dropdownOption:'li[role="option"]',
    textarea: "textarea",
    artifactsTab: "Artifacts",
    dropdown:'p-dropdown',
    contractsTab: 'Retirement Contracts',
    modulesTab: 'Modules',
    schemasTab: 'Schemas',
};

export default CommonElements;