# https://docs.docker.com/compose/environment-variables/envvars-precedence/
# Environment leverage the gerarchy defined in the docker compose between "env_file" and "environment" attributes
# ecosystem variables defined in the "env_file" .env.${GUARDIAN_ENV}.guardian.system
# specific service variables defined by "environment" can override what is defined in the ecosystem file

# YAML anchor that contains common configuration elements for our services
x-service-template: &service-template
  init: true
  env_file:
    - ./configs/.env.${GUARDIAN_ENV}.guardian.system
  environment:
    - GUARDIAN_ENV=${GUARDIAN_ENV}

services:
  mongo:
    image: mongo:6.0.16
    command: "--setParameter allowDiskUseByDefault=true"
    restart: always
    expose:
      - 27017

  cache:
    image: registry.redict.io/redict
    platform: linux/amd64
    restart: always
    expose:
      - 6379

#  seq:
#    image: datalust/seq
#    restart: unless-stopped
#    environment:
#      ACCEPT_EULA: "Y"
#    ports:
#      - "5341:80"
#    volumes:
#      - seq_data:/data

  ipfs-node:
    image: ipfs/kubo:v0.29.0
    ports:
      - "5001:5001"
      - "4001:4001"
      - "8080:8080"
    volumes:
      - ipfs_data:/data/ipfs:rw
      - ipfs_export:/export:rw

  message-broker:
    image: nats:2.9.25
    expose:
      - 4222
    ports:
      - '8222:8222'
    command: '-c /etc/nats/nats.conf --http_port 8222'
    volumes:
      - ./configs/nats.conf:/etc/nats/nats.conf

  vault:
    image: hashicorp/vault:1.12.11
    expose:
      - 8200
    ports:
      - '8200:8200'
    environment:
      VAULT_SERVER: "http://0.0.0.0:8200"
      VAULT_DEV_ROOT_TOKEN_ID: "1234"
    cap_add:
      - IPC_LOCK
    volumes:
      - ./file:/vault/file:rw
      - ./config:/vault/config:rw

  notification-service:
    <<: *service-template
    image: gcr.io/hedera-registry/notification-service:${GUARDIAN_VERSION:-latest}
    depends_on:
      - message-broker
    volumes:
      - ./notification-service/configs:/usr/local/app/configs:ro

  logger-service:
    <<: *service-template
    image: gcr.io/hedera-registry/logger-service:${GUARDIAN_VERSION:-latest}
    depends_on:
      - message-broker
    expose:
      - 6555
    volumes:
      - ./logger-service/configs:/usr/local/app/configs:ro

  queue-service:
    <<: *service-template
    image: gcr.io/hedera-registry/queue-service:${GUARDIAN_VERSION:-latest}
    depends_on:
      - mongo
      - message-broker
      - logger-service
    expose:
      - 6555
    volumes:
      - ./queue-service/configs:/usr/local/app/configs:ro

  worker-service:
    <<: *service-template
    image: gcr.io/hedera-registry/worker-service:${GUARDIAN_VERSION:-latest}
    depends_on:
      queue-service:
        condition: service_started
      ipfs-node:
        condition: service_healthy
      auth-service:
        condition: service_started
    expose:
      - 6555
    volumes:
      - ./worker-service/tls:/usr/local/app/tls:ro
      - ./worker-service/configs:/usr/local/app/configs:ro
    deploy:
      replicas: 2

  auth-service:
    <<: *service-template
    image: gcr.io/hedera-registry/auth-service:${GUARDIAN_VERSION:-latest}
    volumes:
      - ./auth-service/tls:/usr/local/app/tls:ro
      - ./auth-service/configs:/usr/local/app/configs:ro
    depends_on:
      - mongo
      - vault
      - message-broker
      - logger-service
    expose:
      - 6555
      - 5005

  api-gateway:
    <<: *service-template
    image: gcr.io/hedera-registry/api-gateway:${GUARDIAN_VERSION:-latest}
    expose:
      - 3002
      - 6555
    depends_on:
      - mongo
      - cache
#      - seq
      - message-broker
      - guardian-service
      - auth-service
      - logger-service
    volumes:
      - ./api-gateway/configs:/usr/local/app/configs:ro

  ai-service:
    <<: *service-template
    image: gcr.io/hedera-registry/ai-service:${GUARDIAN_VERSION:-latest}
    expose:
      - 3013
    depends_on:
      - mongo
      - message-broker
      - logger-service
    volumes:
      - ./ai-service/faiss-vector:/usr/local/app/faiss-vector:rw
      - ./ai-service/data:/usr/local/app/data:rw
    environment:
      - VECTOR_STORAGE_PATH=./faiss-vector
      - DOCS_STORAGE_PATH=./data/generated-data

  policy-service:
    <<: *service-template
    image: gcr.io/hedera-registry/policy-service:${GUARDIAN_VERSION:-latest}
    depends_on:
      - mongo
      - message-broker
      - auth-service
      - logger-service
    expose:
      - 50000-60000
      - 5006
    volumes:
      - ./policy-service/tls:/usr/local/app/tls:ro
      - ./policy-service/configs:/usr/local/app/configs:ro

  guardian-service:
    <<: *service-template
    image: gcr.io/hedera-registry/guardian-service:${GUARDIAN_VERSION:-latest}
    volumes:
      - ./guardian-service/tls:/usr/local/app/tls:ro
      - ./guardian-service/configs:/usr/local/app/configs:ro
    depends_on:
      - mongo
      - message-broker
      - auth-service
      - logger-service
      - worker-service
      - policy-service
    expose:
      - 6555
      - 5007

  application-events:
    image: gcr.io/hedera-registry/application-events:${GUARDIAN_VERSION:-latest}
    init: true
    depends_on:
      - mongo
      - message-broker
      - guardian-service
      - auth-service
      - logger-service
    expose:
    - 3012

  web-proxy:
    image: gcr.io/hedera-registry/frontend:${GUARDIAN_VERSION:-latest}
    init: true
    environment:
      GATEWAY_CLIENT_MAX_BODY_SIZE: 1024m
      GATEWAY_HOST: api-gateway
      GATEWAY_PORT: 3002
    ports:
      - "3000:80"
    depends_on:
      - guardian-service
      - auth-service
      - api-gateway

  prometheus:
    image: prom/prometheus:v2.44.0
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - "9090:9090"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:10.0.10
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/etc/grafana/dashboards
    environment:
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_SERVER_HTTP_PORT=9080
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/etc/grafana/dashboards/prometheus-dashboard.json
    ports:
      - "9080:9080"
    networks:
      - monitoring

volumes:
  prometheus_data:
  grafana_data:
  ipfs_data:
  ipfs_export:
#  seq_data:

networks:
  monitoring:
    driver: bridge
