version: "3.8"
services:
  mongo:
    image: mongo:6.0.3
    command: "--setParameter allowDiskUseByDefault=true"
    restart: always
    expose:
      - 27017
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express:1.0.0-alpha.4
    expose:
      - 8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_SITE_BASEURL: /mongo-admin
    depends_on:
      - mongo

  # ipfs-node:
  #     image: ipfs/kubo:v0.17.0
  #     ports:
  #       - "5001:5001"
  #       - "5002:5002"
  #       - "4001:4001"
  #       - "4002:4002"
  #       - "8080:8080"
  #       - "8081:8081"

  # api-docs:
  #   build:
  #     context: .
  #     dockerfile: ./api-docs/Dockerfile
  #   expose:
  #     - 3001

  message-broker:
    image: nats:2.9.8
    expose:
      - 4222
    ports:
      - '8222:8222'
      - '4222:4222'
      - '6222:6222'
    command: '--http_port 8222'

  vault:
    image: vault:1.12.2
    expose:
      - 8200
    ports:
      - '8200:8200'
    environment:
      VAULT_SERVER: "http://0.0.0.0:8200"
      VAULT_DEV_ROOT_TOKEN_ID: "1234"
    cap_add:
      - IPC_LOCK
    volumes:
      - ./file:/vault/file:rw
      - ./config:/vault/config:rw
