import { assert } from 'chai';
import {
    ToolMessage,
    ModuleMessage,
    FormulaMessage,
    MessageType,
    MessageAction
} from '../../../dist/hedera-modules/message/index.js';

describe('ToolMessage', () => {
    const body = (over = {}) => ({
        id: 'id', status: 'ISSUE', type: MessageType.Tool, action: MessageAction.CreateVC,
        lang: 'en', account: '0.0.1',
        uuid: 'u1', name: 'tool', description: 'd', owner: 'did:o', hash: 'h1',
        topicId: '0.0.10', tagsTopicId: '0.0.11', version: '1.0.0', ...over
    });

    it('constructs with the Tool type', () => {
        assert.equal(new ToolMessage(MessageType.Tool, MessageAction.CreateVC).type, MessageType.Tool);
    });

    it('fromMessageObject throws on empty json', () => {
        assert.throws(() => ToolMessage.fromMessageObject(null), /JSON Object is empty/);
    });

    it('fromMessageObject throws on a non-Tool type', () => {
        assert.throws(() => ToolMessage.fromMessageObject(body({ type: 'Other' })), /Invalid message type/);
    });

    it('fromMessageObject maps tool fields (topicId → toolTopicId)', () => {
        const m = ToolMessage.fromMessageObject(body());
        assert.equal(m.uuid, 'u1');
        assert.equal(m.name, 'tool');
        assert.equal(m.owner, 'did:o');
        assert.equal(m.hash, 'h1');
        assert.equal(m.toolTopicId, '0.0.10');
        assert.equal(m.tagsTopicId, '0.0.11');
        assert.equal(m.version, '1.0.0');
    });

    it('toDocuments resolves to an array', async () => {
        assert.isArray(await ToolMessage.fromMessageObject(body()).toDocuments());
    });
});

describe('ModuleMessage', () => {
    const body = (over = {}) => ({
        id: 'id', status: 'ISSUE', type: MessageType.Module, action: MessageAction.CreateVC,
        lang: 'en', account: '0.0.1',
        uuid: 'u1', name: 'mod', description: 'd', owner: 'did:o', topicId: '0.0.20', ...over
    });

    it('constructs with the Module type', () => {
        assert.equal(new ModuleMessage(MessageType.Module, MessageAction.CreateVC).type, MessageType.Module);
    });

    it('fromMessageObject throws on empty json', () => {
        assert.throws(() => ModuleMessage.fromMessageObject(null), /JSON Object is empty/);
    });

    it('fromMessageObject throws on a non-Module type', () => {
        assert.throws(() => ModuleMessage.fromMessageObject(body({ type: 'Other' })), /Invalid message type/);
    });

    it('fromMessageObject maps module fields (topicId → moduleTopicId)', () => {
        const m = ModuleMessage.fromMessageObject(body());
        assert.equal(m.uuid, 'u1');
        assert.equal(m.name, 'mod');
        assert.equal(m.owner, 'did:o');
        assert.equal(m.moduleTopicId, '0.0.20');
    });

    it('toDocuments resolves to an array', async () => {
        assert.isArray(await ModuleMessage.fromMessageObject(body()).toDocuments());
    });
});

describe('FormulaMessage', () => {
    const body = (over = {}) => ({
        id: 'id', status: 'ISSUE', type: MessageType.Formula, action: MessageAction.CreateVC,
        lang: 'en', account: '0.0.1',
        uuid: 'u1', name: 'formula', description: 'd', owner: 'did:o',
        policyTopicId: '0.0.30', policyInstanceTopicId: '0.0.31', autoGenerated: true, ...over
    });

    it('constructs with the Formula type', () => {
        assert.equal(new FormulaMessage(MessageAction.CreateVC).type, MessageType.Formula);
    });

    it('fromMessageObject throws on empty json', () => {
        assert.throws(() => FormulaMessage.fromMessageObject(null), /JSON Object is empty/);
    });

    it('fromMessageObject maps formula fields', () => {
        const m = FormulaMessage.fromMessageObject(body());
        assert.equal(m.uuid, 'u1');
        assert.equal(m.name, 'formula');
        assert.equal(m.owner, 'did:o');
        assert.equal(m.policyTopicId, '0.0.30');
        assert.equal(m.policyInstanceTopicId, '0.0.31');
        assert.equal(m.autoGenerated, true);
    });
});
