/**
 * Auth events
 */
export enum AuthEvents {
    GET_USER_BY_TOKEN = 'GET_USER_BY_TOKEN',
    REGISTER_NEW_USER = 'REGISTER_NEW_USER',
    GENERATE_NEW_TOKEN = 'GENERATE_NEW_TOKEN',
    GET_ALL_USER_ACCOUNTS = 'GET_ALL_USER_ACCOUNTS',
    GET_ALL_USER_ACCOUNTS_DEMO = 'GET_ALL_USER_ACCOUNTS_DEMO',
    GET_ALL_STANDARD_REGISTRY_ACCOUNTS = 'GET_ALL_STANDARD_REGISTRY_ACCOUNTS',
    GET_USER = 'GET_USER',
    GET_USER_BY_ID = 'GET_USER_BY_ID',
    GET_USERS_BY_ID = 'GET_USERS_BY_ID',
    GET_USERS_BY_ROLE = 'GET_USERS_BY_ROLE',
    UPDATE_USER = 'UPDATE_USER',
    SAVE_USER = 'SAVE_USER',
    GET_ALL_STANDARD_REGISTRY = 'GET_ALL_STANDARD_REGISTRY',
    GET_USER_BY_ACCOUNT = 'GET_USER_BY_ACCOUNT'
}
