export enum MessageAPI {
    GET_ROOT_ADDRESS_BOOK = 'get-root-address-book',
    GET_ADDRESS_BOOK = 'get-address-book',
    GET_DID_DOCUMENTS = 'get-did-documents',
    GET_VC_DOCUMENTS = 'get-vc-documents',
    SET_DID_DOCUMENT = 'set-did-document',
    SET_VC_DOCUMENT = 'set-vc-document',
    GET_SCHEMES = 'get-schemes',
    SET_SCHEMA = 'set-schema',
    GET_TOKENS = 'get-tokens',
    SET_TOKEN = 'set-token',
    LOAD_DID_DOCUMENT = 'load-did-document',
    LOAD_SCHEMA_DOCUMENT = 'load-schema-document',
    GET_ROOT_CONFIG = 'get-root-config',
    SET_ROOT_CONFIG = 'set-root-config',
    SET_APPROVE_DOCUMENTS = 'set-approve-documents',
    GET_APPROVE_DOCUMENTS = 'get-approve-documents',
    UPDATE_APPROVE_DOCUMENTS = 'update-approve-documents',
    GET_VP_DOCUMENTS = 'get-vp-documents',
    GET_CHAIN = 'get-chain',
    SET_VP_DOCUMENT = 'set-vp-document',
    IMPORT_SCHEMA = "import-schema",
    EXPORT_SCHEMES = "export-schema"
}
