export enum NotificationAction {
    POLICY_CONFIGURATION = 'POLICY_CONFIGURATION',
    POLICY_VIEW = 'POLICY_VIEW',
    POLICIES_PAGE = 'POLICIES_PAGE',
    SCHEMAS_PAGE = 'SCHEMAS_PAGE',
    TOKENS_PAGE = 'TOKENS_PAGE',
    PROFILE_PAGE = 'PROFILE_PAGE',
}
