/**
 * Schema entity
 */
export enum SchemaEntity {
    NONE = 'NONE',
    VC = 'VC',
    EVC = 'EVC',
    STANDARD_REGISTRY = 'STANDARD_REGISTRY',
    USER = 'USER',
    POLICY = 'POLICY',
    MINT_TOKEN = 'MINT_TOKEN',
    RETIRE_TOKEN = 'RETIRE_TOKEN',
    WIPE_TOKEN = 'WIPE_TOKEN',
    MINT_NFTOKEN = 'MINT_NFTOKEN',
    ISSUER = 'ISSUER',
    USER_ROLE = 'USER_ROLE',
    CHUNK = 'CHUNK',
    ACTIVITY_IMPACT = 'ACTIVITY_IMPACT',
    TOKEN_DATA_SOURCE = 'TOKEN_DATA_SOURCE'
}
