/**
 * Schema entity
 */
export enum SchemaEntity {
    NONE = 'NONE',
    VC = 'VC',
    EVC = 'EVC',
    STANDARD_REGISTRY = 'STANDARD_REGISTRY',
    USER = 'USER',
    POLICY = 'POLICY',
    MINT_TOKEN = 'MINT_TOKEN',
    INTEGRATION_DATA_V2 = 'INTEGRATION_DATA_V2',
    RETIRE_TOKEN = 'RETIRE',
    WIPE_TOKEN = 'WIPE_TOKEN',
    MINT_NFTOKEN = 'MINT_NFTOKEN',
    ISSUER = 'ISSUER',
    USER_ROLE = 'USER_ROLE',
    CHUNK = 'CHUNK',
    ACTIVITY_IMPACT = 'ACTIVITY_IMPACT',
    TOKEN_DATA_SOURCE = 'TOKEN_DATA_SOURCE',
    ROLE = 'ROLE',
    USER_PERMISSIONS = 'USER_PERMISSIONS',
    POLICY_DISCUSSION = 'POLICY_DISCUSSION_V2',
    POLICY_COMMENT = 'POLICY_COMMENT',
}
