export enum SchemaEntity {
    NONE = 'NONE',
    INSTALLER = 'INSTALLER',
    INVERTER = 'INVERTER',
    MRV = 'MRV',
    TOKEN = 'TOKEN',
    ROOT_AUTHORITY = 'ROOT_AUTHORITY',
    MINT = 'MINT',
    RETIREMENT = 'RETIREMENT',
    POLICY = 'POLICY',
    POLICY_IMPORTED = 'POLICY_IMPORTED', 
    MINT_TOKEN = 'MINT_TOKEN',
    WIPE_TOKEN = 'WIPE_TOKEN',
    MINT_NFTOKEN = 'MINT_NFTOKEN'
}
