export enum TaskAction {
    CREATE_POLICY = 'Create policy',
    PUBLISH_POLICY = 'Publish policy',
    IMPORT_POLICY_FILE = 'Import policy file',
    IMPORT_POLICY_MESSAGE = 'Import policy message',
    PUBLISH_SCHEMA = 'Publish schema',
    IMPORT_SCHEMA_FILE = 'Import schema file',
    IMPORT_SCHEMA_MESSAGE = 'Import schema message',
    CREATE_SCHEMA = 'Create schema',
    PREVIEW_SCHEMA_MESSAGE = 'Preview schema message',
    CREATE_RANDOM_KEY = 'Create random key',
    CONNECT_USER = 'Connect user',
    PREVIEW_POLICY_MESSAGE = 'Preview policy message',
    CREATE_TOKEN = 'Create token',
    ASSOCIATE_DISSOCIATE_TOKEN = 'Associate/dissociate token',
    GRANT_REVOKE_KYC = 'Grant/revoke KYC',
    DELETE_POLICY = 'Delete policy',
    CLONE_POLICY = 'Clone policy',
    RESTORE_USER_PROFILE = 'Restore user profile',
    GET_USER_TOPICS = 'Get user topics',
}
