"""initial schema

Revision ID: 05cf7b544afe
Revises: 
Create Date: 2026-03-24 21:44:58.253233
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '05cf7b544afe'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('project_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('registry', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_event_type'), 'events', ['event_type'], unique=False)
    op.create_index(op.f('ix_events_project_id'), 'events', ['project_id'], unique=False)
    op.create_index(op.f('ix_events_timestamp'), 'events', ['timestamp'], unique=False)
    op.create_table('project_developers',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('project_count', sa.Integer(), nullable=False),
    sa.Column('total_issued', sa.BigInteger(), nullable=True),
    sa.Column('total_retired', sa.BigInteger(), nullable=True),
    sa.Column('countries', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('registries', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('categories', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('methodologies', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('project_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('registry', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('proponent', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('protocol', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('listed_at', sa.Date(), nullable=True),
    sa.Column('is_compliance', sa.Boolean(), nullable=True),
    sa.Column('retired', sa.BigInteger(), nullable=True),
    sa.Column('issued', sa.BigInteger(), nullable=True),
    sa.Column('first_issuance_at', sa.Date(), nullable=True),
    sa.Column('first_retirement_at', sa.Date(), nullable=True),
    sa.Column('project_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('project_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('project_type_source', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sdg_goals', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('crediting_period_start', sa.Date(), nullable=True),
    sa.Column('crediting_period_end', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('additional_certifications', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('afolu_activities', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('region', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('registration_date', sa.Date(), nullable=True),
    sa.Column('estimated_annual_reductions', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_index(op.f('ix_projects_category'), 'projects', ['category'], unique=False)
    op.create_index(op.f('ix_projects_country'), 'projects', ['country'], unique=False)
    op.create_index(op.f('ix_projects_name'), 'projects', ['name'], unique=False)
    op.create_index(op.f('ix_projects_project_id'), 'projects', ['project_id'], unique=False)
    op.create_index(op.f('ix_projects_proponent'), 'projects', ['proponent'], unique=False)
    op.create_index(op.f('ix_projects_registry'), 'projects', ['registry'], unique=False)
    op.create_index(op.f('ix_projects_status'), 'projects', ['status'], unique=False)
    op.create_table('credits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('quantity', sa.BigInteger(), nullable=True),
    sa.Column('vintage', sa.Integer(), nullable=True),
    sa.Column('transaction_date', sa.Date(), nullable=True),
    sa.Column('transaction_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('retirement_account', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('retirement_beneficiary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('retirement_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('retirement_note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('retirement_beneficiary_harmonized', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('registry', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_planned', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credits_project_id'), 'credits', ['project_id'], unique=False)
    op.create_index(op.f('ix_credits_registry'), 'credits', ['registry'], unique=False)
    op.create_index(op.f('ix_credits_transaction_date'), 'credits', ['transaction_date'], unique=False)
    op.create_index(op.f('ix_credits_transaction_type'), 'credits', ['transaction_type'], unique=False)
    op.create_table('project_developer_links',
    sa.Column('project_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('developer_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['developer_id'], ['project_developers.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.PrimaryKeyConstraint('project_id', 'developer_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_developer_links')
    op.drop_index(op.f('ix_credits_transaction_type'), table_name='credits')
    op.drop_index(op.f('ix_credits_transaction_date'), table_name='credits')
    op.drop_index(op.f('ix_credits_registry'), table_name='credits')
    op.drop_index(op.f('ix_credits_project_id'), table_name='credits')
    op.drop_table('credits')
    op.drop_index(op.f('ix_projects_status'), table_name='projects')
    op.drop_index(op.f('ix_projects_registry'), table_name='projects')
    op.drop_index(op.f('ix_projects_proponent'), table_name='projects')
    op.drop_index(op.f('ix_projects_project_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_name'), table_name='projects')
    op.drop_index(op.f('ix_projects_country'), table_name='projects')
    op.drop_index(op.f('ix_projects_category'), table_name='projects')
    op.drop_table('projects')
    op.drop_table('project_developers')
    op.drop_index(op.f('ix_events_timestamp'), table_name='events')
    op.drop_index(op.f('ix_events_project_id'), table_name='events')
    op.drop_index(op.f('ix_events_event_type'), table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
