"""add_reduction_removal_column

Revision ID: 7d2ef453cc5e
Revises: 05cf7b544afe
Create Date: 2026-03-25 10:15:42.635106
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7d2ef453cc5e'
down_revision: Union[str, None] = '05cf7b544afe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('reduction_removal', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_projects_reduction_removal'), 'projects', ['reduction_removal'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_reduction_removal'), table_name='projects')
    op.drop_column('projects', 'reduction_removal')
    # ### end Alembic commands ###
