"""add corsia_eligible column to projects

Revision ID: 94340ae229fb
Revises: 7d2ef453cc5e
Create Date: 2026-03-27 11:20:46.539761
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '94340ae229fb'
down_revision: Union[str, None] = '7d2ef453cc5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('corsia_eligible', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_projects_corsia_eligible'), 'projects', ['corsia_eligible'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_corsia_eligible'), table_name='projects')
    op.drop_column('projects', 'corsia_eligible')
    # ### end Alembic commands ###
