export enum ApplicationStates {
    STARTED = 'STARTED',
    WRONG_CONFIGURATION = 'WRONG_CONFIGURATION',
    INITIALIZING = 'INITIALIZING',
    READY = 'READY',
    STOPPED = 'STOPPED',
    BAD_CONFIGURATION = 'BAD_CONFIGURATION'
}
