export declare enum PolicyCategoryType {
    SECTORAL_SCOPE = 'SECTORAL_SCOPE',
    PROJECT_SCALE = 'PROJECT_SCALE',
    APPLIED_TECHNOLOGY_TYPE = 'APPLIED_TECHNOLOGY_TYPE',
    MITIGATION_ACTIVITY_TYPE = 'MITIGATION_ACTIVITY_TYPE',
    SUB_TYPE = 'SUB_TYPE'
}
