import { assert } from 'chai';
import { TagIndexer } from '../../../dist/xlsx/models/tag-indexer.js';
import { BlockType } from '@guardian/interfaces';

describe('TagIndexer.getTag', () => {
    it('returns Tool_<n> for BlockType.Tool', () => {
        const ti = new TagIndexer();
        const tag = ti.getTag(BlockType.Tool, null);
        assert.match(tag, /^Tool_\d+$/);
    });

    it('returns "Root_Holder_<n>" for Container with no data', () => {
        const ti = new TagIndexer();
        const tag = ti.getTag(BlockType.Container, null);
        assert.match(tag, /^Root_Holder_\d+$/);
    });

    it('returns "<sanitized>_Schema_Holder_<n>" for Container with data', () => {
        const ti = new TagIndexer();
        const tag = ti.getTag(BlockType.Container, { name: 'My Schema Name' });
        assert.match(tag, /^My_Schema_Name_Schema_Holder_\d+$/);
    });

    it('truncates the data.name prefix to 20 characters', () => {
        const ti = new TagIndexer();
        const longName = 'X'.repeat(40);
        const tag = ti.getTag(BlockType.Container, { name: longName });
        // Prefix is "X" repeated 20 times, then "_Schema_Holder_<n>"
        const prefix = tag.split('_Schema_Holder_')[0];
        assert.equal(prefix.length, 20);
    });

    it('returns "Schema_Entry_<n>" for BlockType.Request', () => {
        const ti = new TagIndexer();
        const tag = ti.getTag(BlockType.Request, null);
        assert.match(tag, /^Schema_Entry_\d+$/);
    });

    it('returns "Schema_Calculations_<n>" for BlockType.CustomLogicBlock', () => {
        const ti = new TagIndexer();
        const tag = ti.getTag(BlockType.CustomLogicBlock, null);
        assert.match(tag, /^Schema_Calculations_\d+$/);
    });

    it('falls back to "Autogenerated_<n>" for any other block type', () => {
        const ti = new TagIndexer();
        const tag = ti.getTag('SOMETHING_ELSE', null);
        assert.match(tag, /^Autogenerated_\d+$/);
    });

    it('emits monotonically increasing indices on subsequent calls', () => {
        const ti = new TagIndexer();
        const a = ti.getTag(BlockType.Request, null);
        const b = ti.getTag(BlockType.Request, null);
        const c = ti.getTag(BlockType.Request, null);
        const idx = (s) => parseInt(s.match(/\d+$/)[0], 10);
        assert.isAbove(idx(b), idx(a));
        assert.isAbove(idx(c), idx(b));
    });
});
