import './accounts/getAccounts.cy'
import './accounts/getBalance.cy'
import './accounts/getRootAuthorities.cy'
import './accounts/getSession.cy'
import './accounts/getStandartReg.cy'
import './accounts/postLogin.cy'
import './accounts/postRegister.cy'
import './external/postExternal.cy'
import './ipfs/postIPFS.cy'
import './logs/getAttributes.cy'
import './logs/postLogs.cy'
// import './policies/getPolicies.cy'
// import './policies/postPoliciesImportFile.cy'
// import './policies/postPoliciesImportMessage.cy'
// import './policies/GetPoliciesAndExportFile.cy'
// import './policies/GetPoliciesAndExportMessage.cy'
// import './policies/getPoliciesBlocks.cy'
// import './policies/getPoliciesBlocksData.cy'
// import './policies/getPolicyTags.cy'
// import './policies/getPolicyId.cy'
// import './profiles/getBalance.cy'
// import './profiles/getProfilesRootUser.cy'
// import './profiles/standardRegistrySetHederaCreds.cy'
// import './profiles/userCreateAndSetHederaCreds.cy'
import './schemas/getSchemas.cy'
import './schemas/getSchemaType.cy'
import './schemas/getSchemaTopicId.cy'
import './schemas/getSchemaEntity.cy'
import './schemas/getSystemSchemaByUser.cy'
import './schemas/getExportSchemaFile.cy'
import './schemas/getExportSchemaMsg.cy'
import './schemas/postImportFile.cy'
import './schemas/postImportFilePreview.cy'
import './schemas/postImportMsg.cy'
import './schemas/postImportMsgPreview.cy'
import './schemas/putActiveSystemSchema.cy'
import './schemas/putSchemaPublish.cy'
import './schemas/putUpdateSchema.cy'
import './schemas/putUpdateSystemSchema.cy'
import './schemas/schemaManage.cy'
import './schemas/systemSchemaManage.cy'
import './settings/getSettings.cy'
import './settings/getSettingsEnv.cy'
import './settings/postSettings.cy'
import './tokens/getTokens.cy'
import './tokens/getUserInfoSelectedToken.cy'
import './tokens/postTokens.cy'
import './tokens/putFreeze.cy'
import './tokens/putGrantKyc.cy'
import './tokens/putRevokeKyc.cy'
import './tokens/putUnfreeze.cy'
import './tokens/putDissociateAssociate.cy'
import './trustchains/getTrustchains.cy'
import './trustchains/getTrustchainsHash.cy'