export enum SectorType {
    RenewableEnergy = 'Renewable Energy',
    Forestry = 'Forestry',
    BlueCarbon = 'Blue Carbon',
    EnergyEfficiency = 'Energy Efficiency',
    Agriculture = 'Agriculture',
    Water = 'Water',
    Waste = 'Waste',
    Energy = 'Energy',
    IndustrialProcess = 'Industrial Process',
    LandUseForestry = 'Land Use & Forestry',
    FugitiveEmissions = 'Fugitive Emissions',
    Transport = 'Transport',
    NatureBasedSolutions = 'Nature Based Solutions',
    Others = 'Others',
    Undefined = 'Undefined',
}

export const SECTOR_I18N_KEYS: Record<string, string> = {
    [SectorType.RenewableEnergy]: 'renewableEnergy',
    [SectorType.Forestry]: 'forestry',
    [SectorType.BlueCarbon]: 'blueCarbon',
    [SectorType.EnergyEfficiency]: 'energyEfficiency',
    [SectorType.Agriculture]: 'agriculture',
    [SectorType.Water]: 'water',
    [SectorType.Waste]: 'waste',
    [SectorType.Energy]: 'energy',
    [SectorType.IndustrialProcess]: 'industrialProcess',
    [SectorType.LandUseForestry]: 'landUseForestry',
    [SectorType.FugitiveEmissions]: 'fugitiveEmissions',
    [SectorType.Transport]: 'transport',
    [SectorType.NatureBasedSolutions]: 'natureBasedSolutions',
    [SectorType.Others]: 'others',
    [SectorType.Undefined]: 'undefined',
};
