export const idGroupKeywords = [
    'id',
    'uuid',
    'topicId',
    'instanceTopicId',
    'synchronizationTopicId',
    'messageId',
    'accountId',
    'tokenId',
    'idType',
];
export const nameGroupKeywords = [
    'name',
    'description',
    'topicDescription',
    'title',
];
export const typeGroupKeywords = [
    'status',
    'type',
    'groupRelationshipType',
    'groupAccessType',
    'blockType',
    'documentType',
    'dataSource',
    'entityType',
    'dataType',
    'input',
    'output',
    'aggregateType',
    'iconType',
    'sortType',
    'dialogType',
    'accountType',
    'typeValue',
];
export const versionGroupKeywords = ['version', 'codeVersion'];
export const userGroupKeywords = [
    'creator',
    'owner',
    'topicOwner',
    'documentSigner',
    'actor',
];
export const tagGroupKeywords = ['policyTag', 'tag'];
export const complexObjGroupKeywords = [
    'config',
    'uiMetaData',
    'children',
    'events',
    'artifacts',
    'options',
];
export const simplePropertiesGroupKeywords = [
    'memoObj',
    'width',
    'schema',
    'topic',
    'expression',
    'outputSchema',
    'value',
    'extention',
    'target',
    'source',
    'tooltip',
    'action',
    'url',
    'dialogContent',
    'dialogClass',
    'bindBlock',
    'uiClass',
    'content',
    'bindGroup',
    'field',
    'presetSchema',
    'period',
    'periodMask',
    'periodInterval',
    'uiSortFieldPath',
    'nextItemField',
    'uiSortByFieldPath',
    'icon',
];
export const dateGroupKeywords = ['createDate', 'startDate', 'endDate'];
export const arrayGroupKeywords = [
    'policyRoles',
    'policyTopics',
    'policyTokens',
    'policyGroups',
    'members',
    'permissions',
    'roles',
    'groups',
    'presetFields',
    'inputFields',
    'fields',
    'filters',
    'buttons',
    'expressions',
    'variables',
    'dynamicFilters',
];
export const flagsGroupKeywords = [
    'static',
    'defaultActive',
    'disabled',
    'enableSorting',
    'onlyOwnDocuments',
    'cyclic',
    'readonly',
    'preset',
    'includeAccounts',
    'changeOwner',
    'onlyOwnByGroupDocuments',
    'stopPropagation',
    'visible',
    'canInvite',
    'canDelete',
    'multiple',
];
export const errorGroupKeywords = ['errorFallbackTag', 'onErrorAction'];
