apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    kompose.controller.type: statefulset
  labels:
    io.kompose.service: message-broker
  name: message-broker
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: message-broker
  serviceName: message-broker
  template:
    metadata:
      labels:
        io.kompose.network/guardian-default: "true"
        io.kompose.service: message-broker
    spec:
      containers:
        - args:
            - --http_port
            - "8222"
          image: nats:2.9.8
          name: message-broker
          ports:
            - containerPort: 8222
            - containerPort: 4222
          resources: {}
      restartPolicy: Always
  updateStrategy: {}
status:
  replicas: 0
