export const DB_NAME = {
    GUARDIAN: 'GUARDIAN',
    TABLES: 'TABLES',
    POLICY_WARNINGS: 'POLICY_WARNINGS',
    COMMENTS: 'COMMENTS',
    HIDE_EVENTS_UI_STATE: 'HIDE_EVENTS_UI_STATE',
}

export const STORES_NAME = {
    POLICY_STORAGE: 'POLICY_STORAGE',
    DOCUMENT_AUTOSAVE_STORAGE: 'DOCUMENT_AUTOSAVE_STORAGE',
    FILES_STORE: 'FILES_STORE',
    DRAFT_STORE: 'DRAFT_STORE',
    FILES_VIEW_STORE: 'FILES_VIEW_STORE',
    IGNORE_RULES_STORE: 'IGNORE_RULES_STORE',
    LAST_READ_COMMENTS: 'LAST_READ_COMMENTS',
    POLICY_HIDE_EVENTS_STORE: 'POLICY_HIDE_EVENTS_STORE',
}
