export const DB_NAME = {
    GUARDIAN: 'GUARDIAN',
    TABLES: 'TABLES',
    POLICY_WARNINGS: 'POLICY_WARNINGS',
}

export const STORES_NAME = {
    POLICY_STORAGE: 'POLICY_STORAGE',
    FILES_STORE: 'FILES_STORE',
    DRAFT_STORE: 'DRAFT_STORE',
    FILES_VIEW_STORE: 'FILES_VIEW_STORE',
    IGNORE_RULES_STORE: 'IGNORE_RULES_STORE',
}
