import { randomInt } from "../../../../support/random";
import * as Authorization from "../../../../support/authorization";
import { HomePage } from "../../pages/homePage";
const homepage = new HomePage();

import { ConfigPage } from "../../pages/configPage";
const configpage = new ConfigPage();

context("Create User Accounts", { tags: ['ui'] }, () => {

    const SRName = "TestSRUI" + randomInt(9999);
    const userName = "TestUserUI" + randomInt(9999);

    // These specs cover the "provide your own Hedera ID and KEY" path, so the credentials
    // have to be typed in rather than generated by the UI. A fresh funded account is
    // requested per run instead of reusing a long-lived one.
    const withNewHederaAccount = (username, callback) =>
        Authorization.getAccessToken(username).then((authorization) => {
            cy.getHederaKeys(authorization).then(callback);
        });

    beforeEach(() => {
        cy.viewport(1920, 1080);
        homepage.visit();
    })

    it("Create Standard Registry by providing Hedera ID and KEY", () => {
        homepage.createAccount("SR", SRName);
        configpage.verifyUserCreated(SRName);
        withNewHederaAccount(SRName, (hederaAccount) => {
            configpage.hederaSRRegistration(hederaAccount.id, hederaAccount.key);
        });
    });

    it("Create User by providing Hedera ID and KEY", () => {
        homepage.createAccount("User", userName);
        configpage.verifyUserCreated(userName);
        withNewHederaAccount(userName, (hederaAccount) => {
            configpage.hederaUserRegistration(SRName, hederaAccount.id, hederaAccount.key);
        });
    });
});
