services:
  cypress-tests:
    build:
      context: .
      dockerfile: Dockerfile.chrome
    image: cypress-build:chrome
    env_file:
      - .env
    environment:
      - CYPRESS_portApi=${CYPRESS_portApi:-4200/}
      - CYPRESS_baseUrl=${CYPRESS_baseUrl:-http://host.docker.internal:4200}
      - CYPRESS_BROWSER=chromium
      - CYPRESS_grepTags=${CYPRESS_grepTags:-all}
      - CYPRESS_grepFilterSpecs=${CYPRESS_grepFilterSpecs:-true}
      - CYPRESS_operatorId=${CYPRESS_operatorId}
      - CYPRESS_operatorKey=${CYPRESS_operatorKey}
      - CYPRESS_MGSAdmin=${CYPRESS_MGSAdmin}
      - CYPRESS_MGSIndexerAPIToken=${CYPRESS_MGSIndexerAPIToken}
    network_mode: "host"
    volumes:
      - ./cypress/reports:/e2e/cypress/reports
      - ./cypress/test_results:/e2e/cypress/test_results
