import assert from 'node:assert/strict';
import { TagIndexer } from '../../../dist/xlsx/models/tag-indexer.js';

describe('TagIndexer', () => {
    it('emits Tool_<n> for BlockType.Tool', () => {
        const idx = new TagIndexer();
        const tag = idx.getTag('tool', null);
        assert.ok(/^Tool_\d+$/.test(tag), `unexpected tag: ${tag}`);
    });

    it('emits Schema_Entry_<n> for Request blocks', () => {
        const idx = new TagIndexer();
        const tag = idx.getTag('requestVcDocumentBlock', null);
        assert.ok(/^Schema_Entry_\d+$/.test(tag), `unexpected tag: ${tag}`);
    });

    it('emits Schema_Calculations_<n> for CustomLogicBlock', () => {
        const idx = new TagIndexer();
        const tag = idx.getTag('customLogicBlock', null);
        assert.ok(/^Schema_Calculations_\d+$/.test(tag));
    });

    it('emits Root_Holder_<n> for Container with no data', () => {
        const idx = new TagIndexer();
        const tag = idx.getTag('interfaceContainerBlock', null);
        assert.ok(/^Root_Holder_\d+$/.test(tag));
    });

    it('emits <name>_Schema_Holder_<n> for Container with named data', () => {
        const idx = new TagIndexer();
        const tag = idx.getTag('interfaceContainerBlock', { name: 'Demo Holder' });
        assert.ok(/^Demo_Holder_Schema_Holder_\d+$/.test(tag), `unexpected tag: ${tag}`);
    });

    it('truncates the name to 20 characters before _Schema_Holder', () => {
        const idx = new TagIndexer();
        const longName = 'x'.repeat(40);
        const tag = idx.getTag('interfaceContainerBlock', { name: longName });
        // The 20-char prefix appears before "_Schema_Holder_<n>".
        const prefix = tag.split('_Schema_Holder_')[0];
        assert.equal(prefix.length, 20);
    });

    it('emits Autogenerated_<n> for unknown block types', () => {
        const idx = new TagIndexer();
        const tag = idx.getTag('unknownBlockType', null);
        assert.ok(/^Autogenerated_\d+$/.test(tag));
    });

    it('produces a unique numeric suffix on each call', () => {
        const idx = new TagIndexer();
        const a = idx.getTag('tool');
        const b = idx.getTag('tool');
        assert.notEqual(a, b);
    });
});
