import type { Content, StyleDictionary, TDocumentDefinitions, TFontDictionary } from 'pdfmake/interfaces';
import { ImpactSummaryResponseDto } from '../../dto/impact-summary.dto';

/**
 * pdfmake docDefinition skeleton for the Impact Summary PDF: running header/footer, title block, badge row,
 * Key Portfolio Metrics, and the full data-section breakdown (Credit Lifecycle, Top Issuances,
 * Geographic/Registry breakdowns, SDG Contributions, Traceability table, Disclosure notes, closing banner).
 *
 * `pdfmake` 0.3.x ships no bundled fonts — `provideFont()` throws unless a font is registered via
 * `pdfMake.setFonts(...)` before `createPdf()`. This file exports `IMPACT_SUMMARY_PDF_FONTS`, mapping a
 * `Helvetica` family to PDFKit's built-in standard-14 font names, so no external .ttf/vfs embedding is needed.
 * This file only builds the `TDocumentDefinitions` object — it never calls `pdfMake` itself, keeping it a pure,
 * easily-unit-testable builder.
 */

// ─────────────────────────────────────────────────────────────────────────
// Fonts
// ─────────────────────────────────────────────────────────────────────────

/** Named font family referenced by `defaultStyle.font` below. */
export const PDF_FONT_FAMILY = 'Helvetica';

/** Font descriptor dictionary for `pdfMake.setFonts(...)`; maps directly onto PDFKit's built-in standard-14 fonts — no font files to ship or embed. */
export const IMPACT_SUMMARY_PDF_FONTS: TFontDictionary = {
    Helvetica: {
        normal: 'Helvetica',
        bold: 'Helvetica-Bold',
        italics: 'Helvetica-Oblique',
        bolditalics: 'Helvetica-BoldOblique',
    },
};

// ─────────────────────────────────────────────────────────────────────────
// Palette + styles (mirrors the design mockup's badge/card colors: green=verified, blue=registries, purple=methodologies, grey=sync/neutral)
// ─────────────────────────────────────────────────────────────────────────

const COLORS = {
    text: '#1f2937',
    muted: '#6b7280',
    border: '#e5e7eb',
    cardBg: '#f9fafb',
    green: '#15803d',
    greenBg: '#dcfce7',
    blue: '#1d4ed8',
    blueBg: '#dbeafe',
    purple: '#6d28d9',
    purpleBg: '#ede9fe',
    grey: '#374151',
    greyBg: '#f3f4f6',
    amber: '#b45309',
    amberBg: '#fef3c7',
    white: '#ffffff',
} as const;

const PDF_STYLES: StyleDictionary = {
    eyebrow: { fontSize: 8, bold: true, color: COLORS.muted, characterSpacing: 0.5 },
    h1: { fontSize: 20, bold: true, color: COLORS.text, margin: [0, 2, 0, 2] },
    subtitle: { fontSize: 9, color: COLORS.muted, margin: [0, 0, 0, 4] },
    badgeText: { fontSize: 8, bold: true },
    metaLabel: { fontSize: 9, color: COLORS.muted },
    metaValue: { fontSize: 9, bold: true, color: COLORS.text },
    metricLabel: { fontSize: 8, color: COLORS.muted },
    metricValue: { fontSize: 18, bold: true, color: COLORS.text, margin: [0, 2, 0, 2] },
    metricSublabel: { fontSize: 7, italics: true, color: COLORS.muted },
    footerNote: { fontSize: 7, color: COLORS.muted },
    // Data-section styles
    sectionHeader: { fontSize: 12, bold: true, color: COLORS.text, margin: [0, 18, 0, 8] },
    cardTitle: { fontSize: 10, bold: true, color: COLORS.text, margin: [0, 0, 0, 8] },
    barLabel: { fontSize: 8, color: COLORS.text },
    barValue: { fontSize: 8, color: COLORS.muted },
    tableHeaderText: { fontSize: 8, bold: true, color: COLORS.muted },
    tableCellText: { fontSize: 8, color: COLORS.text },
    noteText: { fontSize: 8, italics: true, color: COLORS.muted, margin: [0, 6, 0, 0] },
    pillText: { fontSize: 7, bold: true, color: COLORS.white },
    quadTitle: { fontSize: 9, bold: true, color: COLORS.text, margin: [0, 0, 0, 4] },
    quadBody: { fontSize: 8, color: COLORS.muted },
    bannerTitle: { fontSize: 12, bold: true, color: COLORS.green },
    bannerBody: { fontSize: 8, color: COLORS.text },
};

// ─────────────────────────────────────────────────────────────────────────
// Params
// ─────────────────────────────────────────────────────────────────────────

/**
 * Scope filters the report was generated for (Reporting Period / Registry Filter selects). Both are display
 * labels only (already resolved by the caller); this module does no filtering itself. Undefined fields fall
 * back to the "full portfolio" defaults.
 */
export interface ImpactSummaryReportScope {
    /** e.g. "Evercity" or "TolamEarth". Defaults to "All registries". */
    registryLabel?: string;
    /** e.g. "2025" or "Q1 2026". Defaults to "All time". */
    periodLabel?: string;
}

/**
 * Display identity for the closing "Generated by" block. Resolved by the caller (`ImpactSummaryService`) from
 * the authenticated user — this module stays decoupled from `@api/auth/auth.types` and only renders what it is
 * given. `name` is commonly unavailable, so render "--" rather than inventing one.
 */
export interface ImpactSummaryGeneratedBy {
    name?: string | null;
    email?: string | null;
}

export interface ImpactSummaryPdfParams {
    /** The Impact Summary aggregate (already deduped by relatedTopicId/registryDid — see impact-summary.repository.ts). */
    summary: ImpactSummaryResponseDto;
    network: string;
    /** `SA-RPT-{yyyy}-{mmdd}-{seq}` — see report-id.ts. */
    reportId: string;
    scope?: ImpactSummaryReportScope;
    /**
     * Document-generation instant. Passed explicitly (not defaulted to
     * `new Date()` internally) so the header/footer timestamps, the "Data
     * synced" badge, and the caller's `reportId` all agree on the same
     * instant.
     */
    generatedAt: Date;
    /** "Generated by" attribution. Omit to render "--" / "--". */
    generatedBy?: ImpactSummaryGeneratedBy;
}

// ─────────────────────────────────────────────────────────────────────────
// Formatting helpers (exported for reuse by the data-section tables/cards)
// ─────────────────────────────────────────────────────────────────────────

/** `mainnet` -> `Hedera Mainnet` (matches the mockup's "Hedera Mainnet" wording). */
export function networkLabel(network: string): string {
    if (!network) return 'Hedera';
    return `Hedera ${network.charAt(0).toUpperCase()}${network.slice(1)}`;
}

/** `194827` -> `"194,827"`. Rounds to the nearest whole credit (tCO2e are reported as integers throughout the app). */
export function formatNumber(value: number): string {
    return Math.round(value).toLocaleString('en-US');
}

/** `"July 3, 2026"` — used in the running header and the "Data synced" badge. UTC so the label never depends on server TZ. */
export function formatLongDate(date: Date): string {
    return date.toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric', timeZone: 'UTC' });
}

/** `"Jul 3, 2026"` — used in badges. UTC, see formatLongDate. */
export function formatShortDate(date: Date): string {
    return date.toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric', timeZone: 'UTC' });
}

/** `"Jul 3, 2026, 05:02 PM"` — footer "Generated" timestamp. UTC, see formatLongDate. */
export function formatShortDateTime(date: Date): string {
    return date.toLocaleString('en-US', {
        month: 'short',
        day: 'numeric',
        year: 'numeric',
        hour: 'numeric',
        minute: '2-digit',
        hour12: true,
        timeZone: 'UTC',
    });
}

// ─────────────────────────────────────────────────────────────────────────
// Running header / footer
// ─────────────────────────────────────────────────────────────────────────

function buildHeader(network: string, generatedAt: Date): (currentPage: number, pageCount: number) => Content {
    return () => ({
        margin: [40, 24, 40, 0],
        stack: [
            {
                columns: [
                    { text: 'Sustainability Atlas', bold: true, fontSize: 11, color: COLORS.text },
                    {
                        text: [
                            { text: `${networkLabel(network)} · `, color: COLORS.muted, fontSize: 8 },
                            { text: 'Verified', color: COLORS.green, fontSize: 8, bold: true },
                        ],
                        alignment: 'right',
                    },
                ],
            },
            {
                text: `ESG Impact Summary Report · ${formatLongDate(generatedAt)} · Confidential`,
                fontSize: 8,
                color: COLORS.muted,
                margin: [0, 2, 0, 6],
            },
            { canvas: [{ type: 'line', x1: 0, y1: 0, x2: 515, y2: 0, lineWidth: 0.5, lineColor: COLORS.border }] },
        ],
    });
}

function buildFooter(generatedAt: Date): (currentPage: number, pageCount: number) => Content {
    return (currentPage, pageCount) => ({
        margin: [40, 8, 40, 0],
        stack: [
            { canvas: [{ type: 'line', x1: 0, y1: 0, x2: 515, y2: 0, lineWidth: 0.5, lineColor: COLORS.border }] },
            {
                columns: [
                    {
                        width: '*',
                        stack: [
                            {
                                text: 'Data sourced from Hedera Guardian on-chain records. All credits verifiable via HashScan.',
                                style: 'footerNote',
                            },
                            {
                                text: `se.xeptagon.com · Generated ${formatShortDateTime(generatedAt)}`,
                                style: 'footerNote',
                                margin: [0, 1, 0, 0],
                            },
                        ],
                    },
                    { width: 80, text: `Page ${currentPage} of ${pageCount}`, style: 'footerNote', alignment: 'right' },
                ],
                margin: [0, 4, 0, 0],
            },
        ],
    });
}

// ─────────────────────────────────────────────────────────────────────────
// Title block + badge row + Report ID/Network metadata
// ─────────────────────────────────────────────────────────────────────────

function buildTitleBlock(network: string, scope: ImpactSummaryReportScope | undefined): Content[] {
    const registryLabel = scope?.registryLabel ?? 'All registries';
    const periodLabel = scope?.periodLabel ?? 'All time';

    return [
        { text: 'ESG IMPACT SUMMARY REPORT', style: 'eyebrow' },
        { text: 'Carbon Credit Portfolio Overview', style: 'h1' },
        {
            text: `Full portfolio · ${registryLabel} · ${periodLabel} · ${networkLabel(network)}`,
            style: 'subtitle',
        },
    ];
}

/** One colored pill — a borderless single-cell table so `fillColor` (a TableCell-only property) can render a background. */
function badge(text: string, fg: string, bg: string): Content {
    return {
        table: {
            body: [[{ text, style: 'badgeText', color: fg, fillColor: bg, border: [false, false, false, false] }]],
        },
        layout: 'noBorders',
        margin: [0, 0, 8, 4],
    };
}

/**
 * Badge row (Blockchain-Verified / N Registries / N Methodologies / Data synced) + right-aligned Report
 * ID/Network metadata block. Registry/methodology counts come straight from the aggregate, which is already
 * deduped, so no further dedup logic is needed here. "Data synced" has no dedicated sync-watermark field, so
 * this uses the report's own `generatedAt` as the best available proxy.
 */
function buildBadgeRowAndMeta(summary: ImpactSummaryResponseDto, reportId: string, network: string, generatedAt: Date): Content {
    return {
        columns: [
            {
                width: '*',
                columns: [
                    badge('Blockchain-Verified', COLORS.green, COLORS.greenBg),
                    badge(`${summary.registryBreakdown.length} Registries`, COLORS.blue, COLORS.blueBg),
                    badge(`${summary.methodologyCount} Methodologies`, COLORS.purple, COLORS.purpleBg),
                    badge(`Data synced: ${formatShortDate(generatedAt)}`, COLORS.grey, COLORS.greyBg),
                ],
            },
            {
                width: 170,
                alignment: 'right',
                stack: [
                    { text: [{ text: 'Report ID  ', style: 'metaLabel' }, { text: reportId, style: 'metaValue' }] },
                    {
                        text: [{ text: 'Network  ', style: 'metaLabel' }, { text: networkLabel(network), style: 'metaValue' }],
                        margin: [0, 2, 0, 0],
                    },
                ],
            },
        ],
        margin: [0, 14, 0, 0],
    };
}

// ─────────────────────────────────────────────────────────────────────────
// Key Portfolio Metrics (4 stat cards)
// ─────────────────────────────────────────────────────────────────────────

/** One metric card — a borderless single-cell table (same `fillColor` trick as `badge()`) so the card gets a shaded background. */
function metricCard(value: string, label: string, sublabel: string): Content {
    return {
        table: {
            widths: ['*'],
            body: [
                [
                    {
                        stack: [
                            { text: label, style: 'metricLabel' },
                            { text: value, style: 'metricValue' },
                            { text: sublabel, style: 'metricSublabel' },
                        ],
                        fillColor: COLORS.cardBg,
                        border: [false, false, false, false],
                        margin: [10, 10, 10, 10],
                    },
                ],
            ],
        },
        layout: 'noBorders',
    };
}

/** Total Retired is labeled "(inferred)" on the card itself: retirement figures are inferred from Mirror-Node-deleted NFT serials, never an on-chain ledger, and every surface must say so. */
function buildMetricCards(summary: ImpactSummaryResponseDto): Content {
    return {
        columns: [
            metricCard(formatNumber(summary.totalCreditsIssued), 'Total Credits Issued', 'tCO2e issued on-chain'),
            metricCard(formatNumber(summary.totalRetiredInferred), 'Total Retired (inferred)', 'Permanently retired'),
            metricCard(formatNumber(summary.activeSupplyInferred), 'Active Supply', 'Credits in circulation'),
            metricCard(formatNumber(summary.activeProjects), 'Active Projects', 'Verified · Issuing'),
        ],
        columnGap: 10,
        margin: [0, 16, 0, 0],
    };
}

// ─────────────────────────────────────────────────────────────────────────
// Data sections — shared layout helpers
// ─────────────────────────────────────────────────────────────────────────

/** Splits an array into fixed-size chunks (used to lay out the SDG pill grid in rows). */
function chunk<T>(arr: T[], size: number): T[][] {
    const out: T[][] = [];
    for (let i = 0; i < arr.length; i += size) out.push(arr.slice(i, i + size));
    return out;
}

/** `"did:hedera:mainnet:34VqT5em9k..."` — truncates a long DID for a footer caption. `null`/`undefined` renders "--". */
function truncateDid(did: string | null | undefined, visibleChars = 28): string {
    if (!did) return '--';
    if (did.length <= visibleChars + 3) return did;
    return `${did.slice(0, visibleChars)}...`;
}

/**
 * Picks one representative registry DID for the "Registry DID" captions: the scope's named registry if it
 * matches a row in `registryBreakdown`, else the first row that has a DID, else `null`. Never fabricates a DID.
 */
function pickRegistryDid(summary: ImpactSummaryResponseDto, scope: ImpactSummaryReportScope | undefined): string | null {
    if (scope?.registryLabel) {
        const match = summary.registryBreakdown.find((r) => r.displayName === scope.registryLabel && r.registryDid);
        if (match) return match.registryDid;
    }
    return summary.registryBreakdown.find((r) => r.registryDid)?.registryDid ?? null;
}

/** Section heading, matching the report's H2-style headings. */
function sectionHeader(text: string): Content {
    return { text, style: 'sectionHeader' };
}

/** Shaded content card — same `fillColor` single-cell-table trick as `metricCard()`/`badge()` above. */
function card(content: Content[]): Content {
    return {
        table: {
            widths: ['*'],
            body: [[{ stack: content, fillColor: COLORS.cardBg, border: [false, false, false, false], margin: [12, 12, 12, 12] }]],
        },
        layout: 'noBorders',
    };
}

/** Two cards stacked full-width rather than side-by-side, since the inner bar canvases are wider than a half-page column and would clip in a `columns` layout. */
function twoColumnRow(left: Content, right: Content): Content {
    return { stack: [left, { text: '', margin: [0, 3, 0, 0] }, right], margin: [0, 4, 0, 0] };
}

const BAR_WIDTH = 190;
const BAR_HEIGHT = 8;

/** One horizontal bar row: `label | ▇▇▇▇▇____ | value`. Used for sector/geo breakdowns. */
function barRow(label: string, percentage: number, valueLabel: string, color: string): Content {
    const filled = percentage > 0 ? Math.max(3, (percentage / 100) * BAR_WIDTH) : 0;
    return {
        columns: [
            { width: 95, text: label, style: 'barLabel' },
            {
                width: BAR_WIDTH,
                canvas: [
                    { type: 'rect', x: 0, y: 1, w: BAR_WIDTH, h: BAR_HEIGHT, color: COLORS.border },
                    { type: 'rect', x: 0, y: 1, w: filled, h: BAR_HEIGHT, color },
                ],
            },
            { width: '*', text: valueLabel, style: 'barValue', alignment: 'right' },
        ],
        columnGap: 8,
        margin: [0, 3, 0, 3],
    };
}

/** Small colored square + label, used for the Credit Lifecycle legend. */
function legendSwatch(color: string, label: string): Content {
    return {
        columns: [
            { width: 10, canvas: [{ type: 'rect', x: 0, y: 2, w: 8, h: 8, color }] },
            { width: 'auto', text: label, style: 'barValue' },
        ],
        columnGap: 4,
    };
}

function tableHeaderCell(text: string, alignment: 'left' | 'center' | 'right' = 'left'): Content {
    return { text, style: 'tableHeaderText', alignment, fillColor: COLORS.greyBg, margin: [0, 4, 0, 4] };
}

function tableCell(text: string, alignment: 'left' | 'center' | 'right' = 'left'): Content {
    return { text, style: 'tableCellText', alignment };
}

// ─────────────────────────────────────────────────────────────────────────
// Credit Lifecycle + Credits by Sector (2-column row)
// ─────────────────────────────────────────────────────────────────────────

/**
 * Stacked active/retired bar + legend + summary line. Avg vintage year and avg crediting period have no
 * backing field on the aggregate, so they render as "--" rather than invented. Retirement rate is explicitly
 * labeled "inferred": it is derived from Mirror-Node-deleted NFT serials, never a ledger.
 */
function buildCreditLifecycleCard(summary: ImpactSummaryResponseDto): Content {
    const retiredPct = summary.retirementRateInferred;
    const activePct = Math.max(0, Math.round((100 - retiredPct) * 10) / 10);
    const barW = 460;
    const activeW = (activePct / 100) * barW;
    const retiredW = Math.max(0, barW - activeW);

    return card([
        { text: 'Credit Lifecycle', style: 'cardTitle' },
        {
            canvas: [
                { type: 'rect', x: 0, y: 0, w: barW, h: 14, color: COLORS.border },
                { type: 'rect', x: 0, y: 0, w: activeW, h: 14, color: COLORS.green },
                { type: 'rect', x: activeW, y: 0, w: retiredW, h: 14, color: COLORS.amber },
            ],
            margin: [0, 2, 0, 8],
        },
        {
            columns: [
                legendSwatch(COLORS.green, `Active: ${formatNumber(summary.activeSupplyInferred)} (${activePct}%)`),
                legendSwatch(COLORS.amber, `Retired (inferred): ${formatNumber(summary.totalRetiredInferred)} (${retiredPct}%)`),
            ],
            columnGap: 16,
        },
        {
            text: `Retirement rate: ${retiredPct}% (inferred) · Avg vintage year: -- · Avg crediting period: -- yr`,
            style: 'footerNote',
            margin: [0, 8, 0, 0],
        },
    ]);
}

/** Horizontal bar rows per sector, including the explicit 'Unknown'/'Others' buckets already built by `buildSectorBreakdown()` (impact-summary.dto.ts). */
function buildSectorCard(summary: ImpactSummaryResponseDto): Content {
    const rows = summary.sectorBreakdown;
    return card([
        { text: 'Credits by Sector', style: 'cardTitle' },
        ...(rows.length > 0
            ? rows.map((s) => barRow(s.sector, s.percentage, `${s.percentage}% · ${formatNumber(s.creditsIssued)}`, COLORS.purple))
            : [{ text: 'No sector data available.', style: 'footerNote' }]),
    ]);
}

// ─────────────────────────────────────────────────────────────────────────
// Top Issuances by Volume
// ─────────────────────────────────────────────────────────────────────────

/** The aggregate carries no per-issuance rows, so a top-N issuances table cannot be populated without inventing data; renders the table's header shape plus a note that the full dataset lives in the CSV/Excel export. */
function buildTopIssuancesSection(): Content[] {
    return [
        {
            table: {
                headerRows: 1,
                // Equal proportional widths so multi-word headers wrap within the page
                // instead of 'auto' sizing to their unwrapped width (which overflows).
                widths: ['*', '*', '*', '*', '*', '*'],
                body: [
                    [
                        tableHeaderCell('Token / Issuance'),
                        tableHeaderCell('Project'),
                        tableHeaderCell('Registry'),
                        tableHeaderCell('Country'),
                        tableHeaderCell('tCO2e', 'right'),
                        tableHeaderCell('Mint Date', 'right'),
                    ],
                ],
            },
            layout: 'lightHorizontalLines',
        },
        {
            text:
                'Per-issuance detail is not part of this aggregate. Sorted by mint amount descending · ' +
                'full dataset available in CSV/Excel export.',
            style: 'noteText',
        },
    ];
}

// ─────────────────────────────────────────────────────────────────────────
// Geographic Distribution + Credits by Registry (2-column row)
// ─────────────────────────────────────────────────────────────────────────

const GEO_TOP_N = 8;

function buildGeoCard(summary: ImpactSummaryResponseDto): Content {
    const rows = summary.geographicDistribution.slice(0, GEO_TOP_N);
    return card([
        { text: 'Geographic Distribution', style: 'cardTitle' },
        ...(rows.length > 0
            ? rows.map((g) => barRow(g.country, g.percentage, `${formatNumber(g.creditsIssued)}`, COLORS.green))
            : [{ text: 'No geographic data available.', style: 'footerNote' }]),
        {
            text: `${summary.activeCountries} countries · ${summary.activeProjects} active projects`,
            style: 'footerNote',
            margin: [0, 8, 0, 0],
        },
    ]);
}

/** Registry, Projects, Issuances, Credits tCO2e. `registryBreakdown` carries project/issuance/policy counts but no per-registry credit total, so the Credits column always renders "--". */
function buildRegistryTable(summary: ImpactSummaryResponseDto): Content {
    const rows = summary.registryBreakdown;
    const body: Content[][] = [
        [tableHeaderCell('Registry'), tableHeaderCell('Projects', 'center'), tableHeaderCell('Issuances', 'right'), tableHeaderCell('Credits tCO2e', 'right')],
        ...rows.map((r) => [
            tableCell(r.displayName ?? truncateDid(r.registryDid)),
            tableCell(String(r.projectCount), 'center'),
            tableCell(String(r.issuanceCount), 'right'),
            tableCell('--', 'right'),
        ]),
    ];

    return card([
        { text: 'Credits by Registry', style: 'cardTitle' },
        rows.length > 0
            ? { table: { headerRows: 1, widths: ['*', 'auto', 'auto', 'auto'], body }, layout: 'lightHorizontalLines' }
            : { text: 'No registry data available.', style: 'footerNote' },
    ]);
}

// ─────────────────────────────────────────────────────────────────────────
// SDG Contributions
// ─────────────────────────────────────────────────────────────────────────

const SDG_PILLS_PER_ROW = 3;

function sdgPill(sdg: ImpactSummaryResponseDto['sdgContributions'][number]): Content {
    return {
        table: {
            widths: ['*'],
            body: [[{ text: `SDG ${sdg.sdgId} · ${sdg.name}\n${sdg.projectCount} proj`, style: 'pillText', fillColor: sdg.color, border: [false, false, false, false], margin: [8, 6, 8, 6] }]],
        },
        layout: 'noBorders',
        margin: [0, 0, 6, 6],
    };
}

/** Pill grid (chunked 3-per-row) + "N of 17 SDGs addressed" footer, from `summary.sdgContributions` (already sorted by SDG number). */
function buildSdgSection(summary: ImpactSummaryResponseDto): Content[] {
    const sdgs = summary.sdgContributions;
    if (sdgs.length === 0) {
        return [{ text: 'No SDG contributions recorded.', style: 'footerNote' }];
    }

    const topGoal = [...sdgs].sort((a, b) => b.credits - a.credits || b.projectCount - a.projectCount)[0];
    const rows = chunk(sdgs, SDG_PILLS_PER_ROW).map((row) => ({ columns: row.map(sdgPill), columnGap: 6 }) as Content);

    return [
        ...rows,
        {
            text: `${sdgs.length} of 17 SDG addressed · Top goal: SDG ${topGoal.sdgId} ${topGoal.name} (${topGoal.projectCount} projects)`,
            style: 'footerNote',
            margin: [0, 6, 0, 0],
        },
    ];
}

// ─────────────────────────────────────────────────────────────────────────
// Data Traceability & Verification References
// ─────────────────────────────────────────────────────────────────────────

/**
 * The aggregate has no per-record traceability rows — only portfolio-level totals. Renders the table's header
 * shape ("Transaction ID (Hedera)" is its own column, distinct from "Token ID (Registry Record)") plus a note
 * that per-record detail lives in the CSV/Excel export, and a Registry DID footer built from whatever registry
 * the aggregate/scope actually has.
 */
function buildTraceabilitySection(summary: ImpactSummaryResponseDto, network: string, scope: ImpactSummaryReportScope | undefined): Content[] {
    return [
        {
            text: `All records below are verifiable on ${networkLabel(network)} via HashScan · https://hashscan.io/${network}/transaction/{transaction_id}`,
            style: 'footerNote',
            margin: [0, 0, 0, 6],
        },
        {
            table: {
                headerRows: 1,
                // Equal proportional widths so long multi-word headers (and any future
                // URL/timestamp cells) wrap within the page instead of overflowing.
                widths: ['*', '*', '*', '*', '*', '*'],
                body: [
                    [
                        tableHeaderCell('Token Name'),
                        tableHeaderCell('Token ID (Registry Record)'),
                        tableHeaderCell('Transaction ID (Hedera)'),
                        tableHeaderCell('Verification URL'),
                        tableHeaderCell('Source System'),
                        tableHeaderCell('Status'),
                    ],
                ],
            },
            layout: 'lightHorizontalLines',
        },
        {
            text:
                'Per-record traceability detail is not part of this aggregate — see the CSV/Excel export for the ' +
                'complete, per-transaction dataset.',
            style: 'noteText',
        },
        {
            text: `Registry DID: ${truncateDid(pickRegistryDid(summary, scope))} · Network: ${networkLabel(network)}`,
            style: 'footerNote',
            margin: [0, 6, 0, 0],
        },
    ];
}

// ─────────────────────────────────────────────────────────────────────────
// Disclosure & Methodology Notes (4-quadrant text block)
// ─────────────────────────────────────────────────────────────────────────

function quadrant(title: string, body: string): Content {
    return { stack: [{ text: title, style: 'quadTitle' }, { text: body, style: 'quadBody' }] };
}

/** Framework Alignment is static reference copy (not report data); the other three quadrants are parameterized from the real aggregate. */
function buildDisclosureNotesSection(summary: ImpactSummaryResponseDto, network: string): Content[] {
    const net = networkLabel(network);
    const calculation = quadrant(
        'Calculation Methodology',
        `Emissions Reduced (tCO2e) figures are as attested by the issuing registry and anchored on-chain via ` +
            `Hedera Guardian policy workflows. Figures correspond directly to token mint amounts recorded on ${net}.`,
    );
    const governance = quadrant(
        'Data Sources & Governance',
        `All data originates from the Hedera Guardian network (${net}). Registry data across ` +
            `${summary.registryBreakdown.length} registries is imported exclusively from pre-approved sources with ` +
            `automated verification support, per platform import policy.`,
    );
    const framework = quadrant(
        'Framework Alignment',
        'Emissions figures align with the GHG Protocol Corporate Standard (Scope 1 offsets), CDP Climate ' +
            'questionnaire section C11, and GRI 305: Emissions. Vintage year and mitigation type fields support ' +
            'TCFD physical risk disclosures. ISO 14064-3 third-party assurance is available via HashScan ' +
            'transaction verification.',
    );
    const limitations = quadrant(
        'Limitations',
        `Retirement rate is currently ${summary.retirementRateInferred}% (inferred). ${summary.retirementMethodologyNote} ` +
            `SDG contributions are self-reported by project developers via Guardian policy schemas and have not ` +
            `been independently assured. Geographic distribution is at country level only.`,
    );

    return [twoColumnRow(calculation, governance), twoColumnRow(framework, limitations)];
}

// ─────────────────────────────────────────────────────────────────────────
// Closing "Data Verified" banner
// ─────────────────────────────────────────────────────────────────────────

/**
 * Green closing banner + Registry DID + right-aligned "Generated by" block. `generatedBy` comes from the
 * authenticated user threaded through `ImpactSummaryService.buildPdfDocument()` — name/email render "--"
 * when not supplied, never invented.
 */
function buildClosingBanner(
    summary: ImpactSummaryResponseDto,
    network: string,
    scope: ImpactSummaryReportScope | undefined,
    generatedBy: ImpactSummaryGeneratedBy | undefined,
): Content {
    const registryDid = truncateDid(pickRegistryDid(summary, scope));

    return {
        margin: [0, 18, 0, 0],
        table: {
            widths: ['*', 170],
            body: [
                [
                    {
                        stack: [
                            { text: `Data Verified on ${networkLabel(network)}`, style: 'bannerTitle' },
                            {
                                text:
                                    `All figures in this report are derived from Hedera Guardian on-chain records ` +
                                    `and are independently verifiable via HashScan. Registry DID: ${registryDid}`,
                                style: 'bannerBody',
                                margin: [0, 4, 0, 0],
                            },
                        ],
                        fillColor: COLORS.greenBg,
                        border: [false, false, false, false],
                        margin: [14, 14, 14, 14],
                    },
                    {
                        stack: [
                            { text: 'Generated by', style: 'metaLabel', alignment: 'right' },
                            { text: generatedBy?.name || '--', style: 'metaValue', alignment: 'right' },
                            { text: generatedBy?.email || '--', style: 'metaLabel', alignment: 'right', margin: [0, 2, 0, 0] },
                        ],
                        fillColor: COLORS.greenBg,
                        border: [false, false, false, false],
                        margin: [14, 14, 14, 14],
                    },
                ],
            ],
        },
        layout: 'noBorders',
    };
}

// ─────────────────────────────────────────────────────────────────────────
// Assembly
// ─────────────────────────────────────────────────────────────────────────

/** Builds the full pdfmake `TDocumentDefinitions` for the Impact Summary PDF. Pure — no I/O, no `pdfMake.createPdf()` call (that belongs to the streaming endpoint, alongside `IMPACT_SUMMARY_PDF_FONTS`). */
export function buildImpactSummaryPdfDocDefinition(params: ImpactSummaryPdfParams): TDocumentDefinitions {
    const { summary, network, reportId, scope, generatedAt, generatedBy } = params;

    return {
        pageSize: 'A4',
        pageMargins: [40, 90, 40, 60],
        header: buildHeader(network, generatedAt),
        footer: buildFooter(generatedAt),
        defaultStyle: { font: PDF_FONT_FAMILY, fontSize: 9, color: COLORS.text },
        styles: PDF_STYLES,
        info: {
            title: 'ESG Impact Summary Report',
            subject: `Impact Summary — ${networkLabel(network)}`,
            author: 'Sustainability Atlas',
            creator: 'Sustainability Atlas',
        },
        content: [
            ...buildTitleBlock(network, scope),
            buildBadgeRowAndMeta(summary, reportId, network, generatedAt),
            buildMetricCards(summary),

            // Credit Lifecycle + Credits by Sector
            sectionHeader('Credit Lifecycle & Sector Breakdown'),
            twoColumnRow(buildCreditLifecycleCard(summary), buildSectorCard(summary)),

            // Top Issuances by Volume
            sectionHeader('Top Issuances by Volume'),
            ...buildTopIssuancesSection(),

            // Geographic Distribution + Credits by Registry
            sectionHeader('Geographic Distribution & Credits by Registry'),
            twoColumnRow(buildGeoCard(summary), buildRegistryTable(summary)),

            // SDG Contributions
            sectionHeader('SDG Contributions'),
            ...buildSdgSection(summary),

            // Data Traceability & Verification References
            sectionHeader('Data Traceability & Verification References'),
            ...buildTraceabilitySection(summary, network, scope),

            // Disclosure & Methodology Notes
            sectionHeader('Disclosure & Methodology Notes'),
            ...buildDisclosureNotesSection(summary, network),

            // Closing "Data Verified" banner + Generated-by
            buildClosingBanner(summary, network, scope, generatedBy),
        ],
    };
}
