import ExcelJS from 'exceljs';
import { ImpactSummaryResponseDto } from '../../dto/impact-summary.dto';
import { ImpactSummaryGeneratedBy, ImpactSummaryReportScope, formatShortDateTime, networkLabel } from './pdf-template';

/**
 * XLSX/CSV "full dataset" variants of the Impact Summary: PDF is a curated/summarized subset, CSV/Excel is the
 * full raw dataset. The aggregate has no per-issuance/per-transaction rows — only portfolio-level totals and
 * breakdowns — so "full dataset" here means every row of every breakdown the aggregate DOES carry (geographic
 * distribution, sector breakdown, registry breakdown, SDG contributions), unlike the PDF which slices geography
 * to the top 8 countries. Per-record transaction/traceability detail is directed to the `exports` domain
 * instead, never fabricated here.
 */

export interface ImpactSummaryTabularParams {
    summary: ImpactSummaryResponseDto;
    network: string;
    reportId: string;
    scope?: ImpactSummaryReportScope;
    generatedAt: Date;
    generatedBy?: ImpactSummaryGeneratedBy;
}

const TRACEABILITY_NOTE =
    'Per-record transaction/traceability detail (Transaction ID, Registry Record ID, Verification URL, ' +
    'Source System) is not part of this portfolio-level aggregate. For the complete, per-record dataset, use ' +
    'the dataset export endpoints (e.g. GET /api/v1/{network}/exports/credits) which carry those columns.';

/** Total rows across every breakdown section — used as the export's `recordCount`. */
export function countImpactSummaryRows(summary: ImpactSummaryResponseDto): number {
    return (
        summary.geographicDistribution.length +
        summary.sectorBreakdown.length +
        summary.registryBreakdown.length +
        summary.sdgContributions.length
    );
}

function scopeLabels(scope: ImpactSummaryReportScope | undefined): { registry: string; period: string } {
    return {
        registry: scope?.registryLabel ?? 'All registries',
        period: scope?.periodLabel ?? 'All time',
    };
}

// ─────────────────────────────────────────────────────────────────────────
// XLSX (exceljs) — multi-sheet workbook
// ─────────────────────────────────────────────────────────────────────────

function addOverviewSheet(workbook: ExcelJS.Workbook, params: ImpactSummaryTabularParams): void {
    const { summary, network, reportId, generatedAt, generatedBy } = params;
    const { registry, period } = scopeLabels(params.scope);
    const sheet = workbook.addWorksheet('Overview');
    sheet.columns = [
        { header: 'Metric', key: 'metric', width: 32 },
        { header: 'Value', key: 'value', width: 60 },
    ];
    sheet.getRow(1).font = { bold: true };

    const rows: [string, string | number][] = [
        ['Report ID', reportId],
        ['Network', networkLabel(network)],
        ['Registry Scope', registry],
        ['Reporting Period', period],
        ['Generated At', formatShortDateTime(generatedAt)],
        ['Generated By', [generatedBy?.name, generatedBy?.email].filter(Boolean).join(' / ') || '--'],
        ['Total Credits Issued (tCO2e)', summary.totalCreditsIssued],
        ['Total Retired (inferred, tCO2e)', summary.totalRetiredInferred],
        ['Active Supply (inferred, tCO2e)', summary.activeSupplyInferred],
        ['Retirement Rate (inferred, %)', summary.retirementRateInferred],
        ['Active Projects', summary.activeProjects],
        ['Active Countries', summary.activeCountries],
        ['Methodology Count (deduped)', summary.methodologyCount],
        ['Retirement Methodology Note', summary.retirementMethodologyNote],
    ];
    for (const [metric, value] of rows) {
        sheet.addRow({ metric, value });
    }
    sheet.addRow({});
    sheet.addRow({ metric: 'Note', value: TRACEABILITY_NOTE });
}

function addGeoSheet(workbook: ExcelJS.Workbook, summary: ImpactSummaryResponseDto): void {
    const sheet = workbook.addWorksheet('Geographic Distribution');
    sheet.columns = [
        { header: 'Country', key: 'country', width: 24 },
        { header: 'Project Count', key: 'projectCount', width: 16 },
        { header: 'Credits Issued', key: 'creditsIssued', width: 18 },
        { header: 'Percentage', key: 'percentage', width: 14 },
    ];
    sheet.getRow(1).font = { bold: true };
    for (const row of summary.geographicDistribution) {
        sheet.addRow(row);
    }
}

function addSectorSheet(workbook: ExcelJS.Workbook, summary: ImpactSummaryResponseDto): void {
    const sheet = workbook.addWorksheet('Sector Breakdown');
    sheet.columns = [
        { header: 'Sector', key: 'sector', width: 24 },
        { header: 'Is Unknown', key: 'isUnknown', width: 12 },
        { header: 'Is Others', key: 'isOthers', width: 12 },
        { header: 'Project Count', key: 'projectCount', width: 16 },
        { header: 'Credits Issued', key: 'creditsIssued', width: 18 },
        { header: 'Percentage', key: 'percentage', width: 14 },
    ];
    sheet.getRow(1).font = { bold: true };
    for (const row of summary.sectorBreakdown) {
        sheet.addRow(row);
    }
}

function addRegistrySheet(workbook: ExcelJS.Workbook, summary: ImpactSummaryResponseDto): void {
    const sheet = workbook.addWorksheet('Registry Breakdown');
    sheet.columns = [
        { header: 'Registry DID', key: 'registryDid', width: 44 },
        { header: 'Display Name', key: 'displayName', width: 24 },
        { header: 'Project Count', key: 'projectCount', width: 16 },
        { header: 'Issuance Count', key: 'issuanceCount', width: 16 },
        { header: 'Policy Count', key: 'policyCount', width: 14 },
    ];
    sheet.getRow(1).font = { bold: true };
    for (const row of summary.registryBreakdown) {
        sheet.addRow({ ...row, registryDid: row.registryDid ?? '', displayName: row.displayName ?? '' });
    }
}

function addSdgSheet(workbook: ExcelJS.Workbook, summary: ImpactSummaryResponseDto): void {
    const sheet = workbook.addWorksheet('SDG Contributions');
    sheet.columns = [
        { header: 'SDG ID', key: 'sdgId', width: 10 },
        { header: 'Name', key: 'name', width: 34 },
        { header: 'Project Count', key: 'projectCount', width: 16 },
        { header: 'Credits', key: 'credits', width: 16 },
    ];
    sheet.getRow(1).font = { bold: true };
    for (const row of summary.sdgContributions) {
        sheet.addRow({ sdgId: row.sdgId, name: row.name, projectCount: row.projectCount, credits: row.credits });
    }
}

/** Builds the full multi-sheet Impact Summary workbook and returns its bytes. Uses the in-memory `ExcelJS.Workbook` (not the streaming `WorkbookWriter` `XlsxSerializer` uses) since the aggregate's breakdown rows are bounded to a few dozen each, so streaming isn't needed here. */
export async function buildImpactSummaryWorkbookBuffer(params: ImpactSummaryTabularParams): Promise<Buffer> {
    const workbook = new ExcelJS.Workbook();
    workbook.creator = 'Sustainability Atlas';
    workbook.created = params.generatedAt;

    addOverviewSheet(workbook, params);
    addGeoSheet(workbook, params.summary);
    addSectorSheet(workbook, params.summary);
    addRegistrySheet(workbook, params.summary);
    addSdgSheet(workbook, params.summary);

    const arrayBuffer = await workbook.xlsx.writeBuffer();
    return Buffer.from(arrayBuffer);
}

// ─────────────────────────────────────────────────────────────────────────
// CSV — single file, section-delimited
// ─────────────────────────────────────────────────────────────────────────

/** Cell escaping mirrors `csv-serializer.ts`'s `escapeCsvField()`/`cellText()`; duplicated rather than imported since `csv-serializer.ts` only exposes the `Serializer` class, and this module's section-banner rows don't fit that class's single-table contract. */
function cellText(value: unknown): string {
    if (value === null || value === undefined) return '';
    if (value instanceof Date) return value.toISOString();
    return String(value);
}

function escapeCsvField(value: unknown): string {
    const raw = cellText(value);
    if (raw.includes(',') || raw.includes('"') || raw.includes('\n') || raw.includes('\r')) {
        return `"${raw.replace(/"/g, '""')}"`;
    }
    return raw;
}

function csvRow(values: unknown[]): string {
    return values.map(escapeCsvField).join(',');
}

const UTF8_BOM = '﻿';

/** Builds a single CSV file with one section per breakdown, each introduced by a `# Section Title` banner line and its own header row — a tabular representation of the full aggregate in one file, since CSV has no concept of multiple sheets. */
export function buildImpactSummaryCsvBuffer(params: ImpactSummaryTabularParams): Buffer {
    const { summary, network, reportId, generatedAt, generatedBy } = params;
    const { registry, period } = scopeLabels(params.scope);
    const lines: string[] = [];

    lines.push('# Impact Summary Overview');
    lines.push(csvRow(['Metric', 'Value']));
    lines.push(csvRow(['Report ID', reportId]));
    lines.push(csvRow(['Network', networkLabel(network)]));
    lines.push(csvRow(['Registry Scope', registry]));
    lines.push(csvRow(['Reporting Period', period]));
    lines.push(csvRow(['Generated At', formatShortDateTime(generatedAt)]));
    lines.push(csvRow(['Generated By', [generatedBy?.name, generatedBy?.email].filter(Boolean).join(' / ') || '--']));
    lines.push(csvRow(['Total Credits Issued (tCO2e)', summary.totalCreditsIssued]));
    lines.push(csvRow(['Total Retired (inferred, tCO2e)', summary.totalRetiredInferred]));
    lines.push(csvRow(['Active Supply (inferred, tCO2e)', summary.activeSupplyInferred]));
    lines.push(csvRow(['Retirement Rate (inferred, %)', summary.retirementRateInferred]));
    lines.push(csvRow(['Active Projects', summary.activeProjects]));
    lines.push(csvRow(['Active Countries', summary.activeCountries]));
    lines.push(csvRow(['Methodology Count (deduped)', summary.methodologyCount]));
    lines.push(csvRow(['Retirement Methodology Note', summary.retirementMethodologyNote]));
    lines.push('');

    lines.push('# Geographic Distribution');
    lines.push(csvRow(['Country', 'Project Count', 'Credits Issued', 'Percentage']));
    for (const row of summary.geographicDistribution) {
        lines.push(csvRow([row.country, row.projectCount, row.creditsIssued, row.percentage]));
    }
    lines.push('');

    lines.push('# Sector Breakdown');
    lines.push(csvRow(['Sector', 'Is Unknown', 'Is Others', 'Project Count', 'Credits Issued', 'Percentage']));
    for (const row of summary.sectorBreakdown) {
        lines.push(csvRow([row.sector, row.isUnknown, row.isOthers, row.projectCount, row.creditsIssued, row.percentage]));
    }
    lines.push('');

    lines.push('# Registry Breakdown');
    lines.push(csvRow(['Registry DID', 'Display Name', 'Project Count', 'Issuance Count', 'Policy Count']));
    for (const row of summary.registryBreakdown) {
        lines.push(csvRow([row.registryDid ?? '', row.displayName ?? '', row.projectCount, row.issuanceCount, row.policyCount]));
    }
    lines.push('');

    lines.push('# SDG Contributions');
    lines.push(csvRow(['SDG ID', 'Name', 'Project Count', 'Credits']));
    for (const row of summary.sdgContributions) {
        lines.push(csvRow([row.sdgId, row.name, row.projectCount, row.credits]));
    }
    lines.push('');

    lines.push('# Notes');
    lines.push(csvRow([TRACEABILITY_NOTE]));

    return Buffer.from(UTF8_BOM + lines.join('\r\n'), 'utf-8');
}
