---
apiVersion: v1
kind: ConfigMap
data:
  default.conf: |
    server {
      listen       80;
      listen  [::]:80;
      server_name  localhost;

      location / {
          root   /usr/share/nginx/html;
          try_files $uri $uri/ /index.html;
      }
    }

metadata:
  name: frontend-service-nginx-conf
