import { BlockType, GenerateUUIDv4, SchemaEntity } from '@guardian/interfaces';
import { XlsxResult } from './models/xlsx-result';
import { Policy, PolicyTool } from '../entity';
import { IBlock } from './interfaces/block-interface';
import { XlsxSchema } from './models/xlsx-schema';
import * as mathjs from 'mathjs';

class TagIndexer {
    private index: number;

    constructor() {
        this.index = Date.now();
    }

    public getTag(): string {
        return `Autogenerated_${++this.index}`;
    }
}

interface IExpression {
    symbol: string;
    formulae: string;
}

interface IVariable {
    symbol: string;
    path: string;
}

/**
 * Generate policy config
 */
export class GenerateBlocks {
    /**
     * Generate policy config
     * @param xlsxResult
     */
    public static generate(xlsxResult: XlsxResult) {
        const tags = new TagIndexer();
        const parent = GenerateBlocks.generateContainer(xlsxResult.policy, tags);
        GenerateBlocks.addPolicyTools(xlsxResult.policy, xlsxResult.tools, parent, tags);
        GenerateBlocks.generateRequests(xlsxResult.xlsxSchemas, parent, tags, xlsxResult);
    }

    /**
     * Add block
     * @param parent
     * @param block
     */
    private static pushBlock(parent: IBlock, block: IBlock) {
        if (Array.isArray(parent.children)) {
            parent.children.push(block);
        } else {
            parent.children = [block];
        }
    }

    /**
     * Add block
     * @param parent
     * @param block
     */
    private static unshiftBlock(parent: IBlock, block: IBlock) {
        if (Array.isArray(parent.children)) {
            parent.children.unshift(block);
        } else {
            parent.children = [block];
        }
    }

    /**
     * Generate block
     * @param config
     */
    private static generateBlock(config: any): IBlock {
        return {
            id: GenerateUUIDv4(),
            defaultActive: true,
            children: [],
            permissions: [],
            artifacts: [],
            ...config
        } as IBlock;
    }

    /**
     * Find tool ids
     * @param block
     * @param result
     */
    private static findTools(block: any, result: Set<string>) {
        if (!block) {
            return;
        }
        if (block.blockType === BlockType.Tool) {
            if (block.messageId && typeof block.messageId === 'string') {
                result.add(block.messageId);
            }
        } else {
            if (Array.isArray(block.children)) {
                for (const child of block.children) {
                    GenerateBlocks.findTools(child, result);
                }
            }
        }
    }

    /**
     * Generate Tool
     * @param policy
     * @param tools
     */
    private static addPolicyTools(
        policy: Policy,
        tools: PolicyTool[],
        parent: IBlock,
        tags: TagIndexer
    ): void {
        const toolIds = new Set<string>();
        GenerateBlocks.findTools(policy.config, toolIds);
        for (const tool of tools) {
            if (!toolIds.has(tool.messageId)) {
                toolIds.add(tool.messageId);
                const block = GenerateBlocks.generateBlock({
                    tag: tags.getTag(),
                    blockType: BlockType.Tool,
                    hash: tool.hash,
                    messageId: tool.messageId,
                    inputEvents: tool.config?.inputEvents,
                    outputEvents: tool.config?.outputEvents,
                    variables: tool.config?.variables,
                    innerEvents: []
                })
                GenerateBlocks.pushBlock(parent, block);
            }
        }
    }

    /**
     * Generate Container
     * @param policy
     * @param schemas
     */
    private static generateContainer(
        policy: Policy,
        tags: TagIndexer
    ): IBlock {
        const parent = GenerateBlocks.generateBlock({
            tag: tags.getTag(),
            blockType: BlockType.Container
        });
        GenerateBlocks.unshiftBlock(policy.config, parent);
        return parent;
    }

    /**
     * Generate Requests
     * @param policy
     * @param schemas
     */
    private static generateRequests(
        schemas: XlsxSchema[],
        parent: IBlock,
        tags: TagIndexer,
        xlsxResult: XlsxResult
    ): void {
        for (const schema of schemas) {
            if (schema.entity === SchemaEntity.VC) {
                const requestContainer = GenerateBlocks.generateBlock({
                    tag: tags.getTag(),
                    blockType: BlockType.Container
                });
                GenerateBlocks.generateRequest(requestContainer, schema, tags);
                GenerateBlocks.generateCalculation(requestContainer, schema, tags, xlsxResult);
                GenerateBlocks.pushBlock(parent, requestContainer);
            }
        }
    }

    /**
     * Generate Request
     * @param parent
     * @param schema
     */
    private static generateRequest(
        parent: IBlock,
        schema: XlsxSchema,
        tags: TagIndexer
    ): void {
        const request = GenerateBlocks.generateBlock({
            tag: tags.getTag(),
            blockType: BlockType.Request,
            schema: schema.iri,
            idType: 'UUID',
            presetFields: []
        });
        GenerateBlocks.pushBlock(parent, request);
    }

    /**
     * Generate CustomLogicBlock
     * @param parent
     * @param schema
     */
    private static generateCalculation(
        parent: IBlock,
        schema: XlsxSchema,
        tags: TagIndexer,
        xlsxResult: XlsxResult
    ): void {
        const expression = GenerateBlocks.generateExpression(schema, xlsxResult);
        if (expression) {
            const calculation = GenerateBlocks.generateBlock({
                tag: tags.getTag(),
                blockType: BlockType.CustomLogicBlock,
                expression,
                documentSigner: '',
                idType: 'UUID',
                outputSchema: schema.iri,
            });
            GenerateBlocks.pushBlock(parent, calculation);
        }
    }

    /**
     * Generate Expression
     * @param schema
     */
    private static generateExpression(
        xlsxSchema: XlsxSchema,
        xlsxResult: XlsxResult
    ): string {
        const expressions: IExpression[] = [];
        for (const field of xlsxSchema.fields) {
            if (field.formulae) {
                expressions.push({
                    symbol: field.name,
                    formulae: field.formulae
                });
            }
        }
        if (!expressions.length) {
            return null;
        }

        const symbols = new Set<string>();
        for (const expression of expressions) {
            const nodes = mathjs.parse(expression.formulae);
            GenerateBlocks.findVariables(nodes, symbols);
        }

        const variables: IVariable[] = [];
        const paths = xlsxSchema.getVariables();
        for (const symbol of symbols) {
            if (paths.has(symbol)) {
                variables.push({
                    symbol,
                    path: paths.get(symbol)
                });
            } else {
                xlsxResult.addError({
                    type: 'error',
                    text: `Variable ${symbol} is not defined.`,
                    message: `Variable ${symbol} is not defined.`,
                    worksheet: xlsxSchema.worksheet.name
                }, null);
                return null;
            }
        }

        let body = '';
        //Main
        body += `function main(document) {\r\n`;
        body += `    //Variables\r\n`;
        //Variables
        for (const variable of variables) {
            body += `    let ${variable.symbol} = document.${variable.path};\r\n`;
        }
        body += `\r\n`;
        //Expressions
        body += `    //Expressions\r\n`;
        for (const expression of expressions) {
            body += `    document.${expression.symbol} = ${expression.formulae};\r\n \\\\${xlsxSchema.worksheet.name}: ${expression.symbol} = ${expression.formulae}`;
        }
        body += `\r\n`;
        //Main
        body += `    //Result\r\n`;
        body += `    return document;\r\n`;
        body += `}\r\n`;
        body += `(function calc() {\r\n`;
        body += `    return done(documents.map((document) =>\r\n`;
        body += `        main(document.document.credentialSubject[0]);\r\n`;
        body += `    ));\r\n`;
        body += `})();`;

        return body;
    }

    private static findVariables(tree: mathjs.MathNode, variables: Set<string>): void {
        if (tree.type === 'SymbolNode') {
            variables.add(tree.name);
        } else if (tree.type === 'FunctionNode' || tree.type === 'OperatorNode') {
            for (const arg of tree.args) {
                GenerateBlocks.findVariables(arg, variables);
            }
        }
    }
}