/**
 * Country-code lookup tables mirroring frontend/composables/useProjects.ts's
 * COUNTRY_ALPHA3 / ALPHA3_TO_NAME / resolveCountryCode - used by
 * PgProjectRepository's country filter so selecting a country matches every
 * raw stored variant (e.g. "MEX" and "Mexico" both count as Mexico), the
 * same grouping the frontend already applies for display. Generated from
 * that file's data; keep the two in sync when it changes (separate
 * frontend/backend TS projects, not shared code).
 */

/**
 * Sentinel accepted by the Projects country filter to mean "every project
 * whose stored country isn't a recognized ISO 3166-1 name/alpha-3 code" -
 * the same bucket the frontend displays as "Other" (see
 * frontend/composables/useProjects.ts's resolveCountryCode/OTHER_COUNTRY).
 * A plain ILIKE can't express that (it can only match specific substrings),
 * so PgProjectRepository special-cases this value into a NOT-IN-list clause.
 */
export const OTHER_COUNTRY_FILTER_VALUE = '__other__';

/** Lowercased ISO 3166-1 country name/alias/alpha-3-code token, mapped to its canonical alpha-3 code. */
export const COUNTRY_TOKEN_TO_CODE: Record<string, string> = {
    'afghanistan': 'AFG',
    'albania': 'ALB',
    'algeria': 'DZA',
    'andorra': 'AND',
    'angola': 'AGO',
    'antigua and barbuda': 'ATG',
    'argentina': 'ARG',
    'armenia': 'ARM',
    'australia': 'AUS',
    'austria': 'AUT',
    'azerbaijan': 'AZE',
    'bahamas': 'BHS',
    'bahrain': 'BHR',
    'bangladesh': 'BGD',
    'barbados': 'BRB',
    'belarus': 'BLR',
    'belgium': 'BEL',
    'belize': 'BLZ',
    'benin': 'BEN',
    'bhutan': 'BTN',
    'bolivia': 'BOL',
    'bosnia and herzegovina': 'BIH',
    'botswana': 'BWA',
    'brazil': 'BRA',
    'brunei': 'BRN',
    'brunei darussalam': 'BRN',
    'bulgaria': 'BGR',
    'burkina faso': 'BFA',
    'burundi': 'BDI',
    'cabo verde': 'CPV',
    'cape verde': 'CPV',
    'cambodia': 'KHM',
    'cameroon': 'CMR',
    'canada': 'CAN',
    'central african republic': 'CAF',
    'chad': 'TCD',
    'chile': 'CHL',
    'china': 'CHN',
    'colombia': 'COL',
    'comoros': 'COM',
    'congo': 'COG',
    'republic of the congo': 'COG',
    'costa rica': 'CRI',
    'croatia': 'HRV',
    'cuba': 'CUB',
    'cyprus': 'CYP',
    'czech republic': 'CZE',
    'czechia': 'CZE',
    'denmark': 'DNK',
    'djibouti': 'DJI',
    'dominica': 'DMA',
    'dominican republic': 'DOM',
    'dr congo': 'COD',
    'democratic republic of the congo': 'COD',
    'ecuador': 'ECU',
    'egypt': 'EGY',
    'el salvador': 'SLV',
    'equatorial guinea': 'GNQ',
    'eritrea': 'ERI',
    'estonia': 'EST',
    'eswatini': 'SWZ',
    'swaziland': 'SWZ',
    'ethiopia': 'ETH',
    'fiji': 'FJI',
    'finland': 'FIN',
    'france': 'FRA',
    'gabon': 'GAB',
    'gambia': 'GMB',
    'georgia': 'GEO',
    'germany': 'DEU',
    'ghana': 'GHA',
    'greece': 'GRC',
    'grenada': 'GRD',
    'guatemala': 'GTM',
    'guinea': 'GIN',
    'guinea-bissau': 'GNB',
    'guyana': 'GUY',
    'haiti': 'HTI',
    'honduras': 'HND',
    'hungary': 'HUN',
    'hong kong': 'HKG',
    'iceland': 'ISL',
    'india': 'IND',
    'indonesia': 'IDN',
    'iran': 'IRN',
    'iraq': 'IRQ',
    'ireland': 'IRL',
    'israel': 'ISR',
    'italy': 'ITA',
    'ivory coast': 'CIV',
    'côte d\'ivoire': 'CIV',
    'cote d\'ivoire': 'CIV',
    'jamaica': 'JAM',
    'japan': 'JPN',
    'jordan': 'JOR',
    'kazakhstan': 'KAZ',
    'kenya': 'KEN',
    'kiribati': 'KIR',
    'kuwait': 'KWT',
    'kyrgyzstan': 'KGZ',
    'laos': 'LAO',
    'lao pdr': 'LAO',
    'lao people\'s democratic republic': 'LAO',
    'latvia': 'LVA',
    'lebanon': 'LBN',
    'lesotho': 'LSO',
    'liberia': 'LBR',
    'libya': 'LBY',
    'liechtenstein': 'LIE',
    'lithuania': 'LTU',
    'luxembourg': 'LUX',
    'madagascar': 'MDG',
    'malawi': 'MWI',
    'malaysia': 'MYS',
    'maldives': 'MDV',
    'mali': 'MLI',
    'malta': 'MLT',
    'marshall islands': 'MHL',
    'mauritania': 'MRT',
    'mauritius': 'MUS',
    'mexico': 'MEX',
    'micronesia': 'FSM',
    'moldova': 'MDA',
    'monaco': 'MCO',
    'mongolia': 'MNG',
    'montenegro': 'MNE',
    'morocco': 'MAR',
    'mozambique': 'MOZ',
    'myanmar': 'MMR',
    'burma': 'MMR',
    'mex': 'MEX',
    'macau': 'MAC',
    'namibia': 'NAM',
    'nauru': 'NRU',
    'nepal': 'NPL',
    'netherlands': 'NLD',
    'new zealand': 'NZL',
    'nicaragua': 'NIC',
    'niger': 'NER',
    'nigeria': 'NGA',
    'north korea': 'PRK',
    'north macedonia': 'MKD',
    'macedonia': 'MKD',
    'norway': 'NOR',
    'oman': 'OMN',
    'pakistan': 'PAK',
    'palau': 'PLW',
    'palestine': 'PSE',
    'panama': 'PAN',
    'papua new guinea': 'PNG',
    'paraguay': 'PRY',
    'peru': 'PER',
    'perú': 'PER',
    'philippines': 'PHL',
    'poland': 'POL',
    'portugal': 'PRT',
    'puerto rico': 'PRI',
    'qatar': 'QAT',
    'romania': 'ROU',
    'russia': 'RUS',
    'russian federation': 'RUS',
    'rwanda': 'RWA',
    'réunion': 'REU',
    'saint kitts and nevis': 'KNA',
    'saint lucia': 'LCA',
    'saint vincent and the grenadines': 'VCT',
    'samoa': 'WSM',
    'san marino': 'SMR',
    'sao tome and principe': 'STP',
    'saudi arabia': 'SAU',
    'senegal': 'SEN',
    'serbia': 'SRB',
    'seychelles': 'SYC',
    'sierra leone': 'SLE',
    'singapore': 'SGP',
    'slovakia': 'SVK',
    'slovenia': 'SVN',
    'solomon islands': 'SLB',
    'somalia': 'SOM',
    'south africa': 'ZAF',
    'south korea': 'KOR',
    'republic of korea': 'KOR',
    'south sudan': 'SSD',
    'spain': 'ESP',
    'sri lanka': 'LKA',
    'sudan': 'SDN',
    'suriname': 'SUR',
    'sweden': 'SWE',
    'switzerland': 'CHE',
    'syria': 'SYR',
    'syrian arab republic': 'SYR',
    'taiwan': 'TWN',
    'tajikistan': 'TJK',
    'tanzania': 'TZA',
    'united republic of tanzania': 'TZA',
    'thailand': 'THA',
    'timor-leste': 'TLS',
    'east timor': 'TLS',
    'togo': 'TGO',
    'tonga': 'TON',
    'trinidad and tobago': 'TTO',
    'tunisia': 'TUN',
    'turkey': 'TUR',
    'türkiye': 'TUR',
    'turkmenistan': 'TKM',
    'tuvalu': 'TUV',
    'uganda': 'UGA',
    'ukraine': 'UKR',
    'united arab emirates': 'ARE',
    'uae': 'ARE',
    'united kingdom': 'GBR',
    'united states': 'USA',
    'united states of america': 'USA',
    'uruguay': 'URY',
    'uzbekistan': 'UZB',
    'vanuatu': 'VUT',
    'vatican city': 'VAT',
    'venezuela': 'VEN',
    'vietnam': 'VNM',
    'viet nam': 'VNM',
    'yemen': 'YEM',
    'zambia': 'ZMB',
    'zimbabwe': 'ZWE',
    'afg': 'AFG',
    'alb': 'ALB',
    'dza': 'DZA',
    'and': 'AND',
    'ago': 'AGO',
    'atg': 'ATG',
    'arg': 'ARG',
    'arm': 'ARM',
    'aus': 'AUS',
    'aut': 'AUT',
    'aze': 'AZE',
    'bhs': 'BHS',
    'bhr': 'BHR',
    'bgd': 'BGD',
    'brb': 'BRB',
    'blr': 'BLR',
    'bel': 'BEL',
    'blz': 'BLZ',
    'ben': 'BEN',
    'btn': 'BTN',
    'bol': 'BOL',
    'bih': 'BIH',
    'bwa': 'BWA',
    'bra': 'BRA',
    'brn': 'BRN',
    'bgr': 'BGR',
    'bfa': 'BFA',
    'bdi': 'BDI',
    'cpv': 'CPV',
    'khm': 'KHM',
    'cmr': 'CMR',
    'can': 'CAN',
    'caf': 'CAF',
    'tcd': 'TCD',
    'chl': 'CHL',
    'chn': 'CHN',
    'col': 'COL',
    'com': 'COM',
    'cog': 'COG',
    'cri': 'CRI',
    'hrv': 'HRV',
    'cub': 'CUB',
    'cyp': 'CYP',
    'cze': 'CZE',
    'dnk': 'DNK',
    'dji': 'DJI',
    'dma': 'DMA',
    'dom': 'DOM',
    'cod': 'COD',
    'ecu': 'ECU',
    'egy': 'EGY',
    'slv': 'SLV',
    'gnq': 'GNQ',
    'eri': 'ERI',
    'est': 'EST',
    'swz': 'SWZ',
    'eth': 'ETH',
    'fji': 'FJI',
    'fin': 'FIN',
    'fra': 'FRA',
    'gab': 'GAB',
    'gmb': 'GMB',
    'geo': 'GEO',
    'deu': 'DEU',
    'gha': 'GHA',
    'grc': 'GRC',
    'grd': 'GRD',
    'gtm': 'GTM',
    'gin': 'GIN',
    'gnb': 'GNB',
    'guy': 'GUY',
    'hti': 'HTI',
    'hnd': 'HND',
    'hun': 'HUN',
    'hkg': 'HKG',
    'isl': 'ISL',
    'ind': 'IND',
    'idn': 'IDN',
    'irn': 'IRN',
    'irq': 'IRQ',
    'irl': 'IRL',
    'isr': 'ISR',
    'ita': 'ITA',
    'civ': 'CIV',
    'jam': 'JAM',
    'jpn': 'JPN',
    'jor': 'JOR',
    'kaz': 'KAZ',
    'ken': 'KEN',
    'kir': 'KIR',
    'kwt': 'KWT',
    'kgz': 'KGZ',
    'lao': 'LAO',
    'lva': 'LVA',
    'lbn': 'LBN',
    'lso': 'LSO',
    'lbr': 'LBR',
    'lby': 'LBY',
    'lie': 'LIE',
    'ltu': 'LTU',
    'lux': 'LUX',
    'mdg': 'MDG',
    'mwi': 'MWI',
    'mys': 'MYS',
    'mdv': 'MDV',
    'mli': 'MLI',
    'mlt': 'MLT',
    'mhl': 'MHL',
    'mrt': 'MRT',
    'mus': 'MUS',
    'fsm': 'FSM',
    'mda': 'MDA',
    'mco': 'MCO',
    'mng': 'MNG',
    'mne': 'MNE',
    'mar': 'MAR',
    'moz': 'MOZ',
    'mmr': 'MMR',
    'mac': 'MAC',
    'nam': 'NAM',
    'nru': 'NRU',
    'npl': 'NPL',
    'nld': 'NLD',
    'nzl': 'NZL',
    'nic': 'NIC',
    'ner': 'NER',
    'nga': 'NGA',
    'prk': 'PRK',
    'mkd': 'MKD',
    'nor': 'NOR',
    'omn': 'OMN',
    'pak': 'PAK',
    'plw': 'PLW',
    'pse': 'PSE',
    'pan': 'PAN',
    'png': 'PNG',
    'pry': 'PRY',
    'per': 'PER',
    'phl': 'PHL',
    'pol': 'POL',
    'prt': 'PRT',
    'pri': 'PRI',
    'qat': 'QAT',
    'rou': 'ROU',
    'rus': 'RUS',
    'rwa': 'RWA',
    'reu': 'REU',
    'kna': 'KNA',
    'lca': 'LCA',
    'vct': 'VCT',
    'wsm': 'WSM',
    'smr': 'SMR',
    'stp': 'STP',
    'sau': 'SAU',
    'sen': 'SEN',
    'srb': 'SRB',
    'syc': 'SYC',
    'sle': 'SLE',
    'sgp': 'SGP',
    'svk': 'SVK',
    'svn': 'SVN',
    'slb': 'SLB',
    'som': 'SOM',
    'zaf': 'ZAF',
    'kor': 'KOR',
    'ssd': 'SSD',
    'esp': 'ESP',
    'lka': 'LKA',
    'sdn': 'SDN',
    'sur': 'SUR',
    'swe': 'SWE',
    'che': 'CHE',
    'syr': 'SYR',
    'twn': 'TWN',
    'tjk': 'TJK',
    'tza': 'TZA',
    'tha': 'THA',
    'tls': 'TLS',
    'tgo': 'TGO',
    'ton': 'TON',
    'tto': 'TTO',
    'tun': 'TUN',
    'tur': 'TUR',
    'tkm': 'TKM',
    'tuv': 'TUV',
    'uga': 'UGA',
    'ukr': 'UKR',
    'are': 'ARE',
    'gbr': 'GBR',
    'usa': 'USA',
    'ury': 'URY',
    'uzb': 'UZB',
    'vut': 'VUT',
    'vat': 'VAT',
    'ven': 'VEN',
    'vnm': 'VNM',
    'yem': 'YEM',
    'zmb': 'ZMB',
    'zwe': 'ZWE',
};

/** Every recognized token (name, alias, or alpha-3 code, lowercased) - the "Other" filter's NOT-IN-list. */
export const RECOGNIZED_COUNTRY_TOKENS: string[] = Object.keys(COUNTRY_TOKEN_TO_CODE);

/** Alpha-3 code, mapped to every lowercased raw form (name, alias, or the code itself) a stored project country might use for it. */
export const CODE_TO_ALIASES: Record<string, string[]> = {
    'AFG': ['afg', 'afghanistan'],
    'ALB': ['alb', 'albania'],
    'DZA': ['algeria', 'dza'],
    'AND': ['and', 'andorra'],
    'AGO': ['ago', 'angola'],
    'ATG': ['antigua and barbuda', 'atg'],
    'ARG': ['arg', 'argentina'],
    'ARM': ['arm', 'armenia'],
    'AUS': ['aus', 'australia'],
    'AUT': ['austria', 'aut'],
    'AZE': ['aze', 'azerbaijan'],
    'BHS': ['bahamas', 'bhs'],
    'BHR': ['bahrain', 'bhr'],
    'BGD': ['bangladesh', 'bgd'],
    'BRB': ['barbados', 'brb'],
    'BLR': ['belarus', 'blr'],
    'BEL': ['bel', 'belgium'],
    'BLZ': ['belize', 'blz'],
    'BEN': ['ben', 'benin'],
    'BTN': ['bhutan', 'btn'],
    'BOL': ['bol', 'bolivia'],
    'BIH': ['bih', 'bosnia and herzegovina'],
    'BWA': ['botswana', 'bwa'],
    'BRA': ['bra', 'brazil'],
    'BRN': ['brn', 'brunei', 'brunei darussalam'],
    'BGR': ['bgr', 'bulgaria'],
    'BFA': ['bfa', 'burkina faso'],
    'BDI': ['bdi', 'burundi'],
    'CPV': ['cabo verde', 'cape verde', 'cpv'],
    'KHM': ['cambodia', 'khm'],
    'CMR': ['cameroon', 'cmr'],
    'CAN': ['can', 'canada'],
    'CAF': ['caf', 'central african republic'],
    'TCD': ['chad', 'tcd'],
    'CHL': ['chile', 'chl'],
    'CHN': ['china', 'chn'],
    'COL': ['col', 'colombia'],
    'COM': ['com', 'comoros'],
    'COG': ['cog', 'congo', 'republic of the congo'],
    'CRI': ['costa rica', 'cri'],
    'HRV': ['croatia', 'hrv'],
    'CUB': ['cub', 'cuba'],
    'CYP': ['cyp', 'cyprus'],
    'CZE': ['cze', 'czech republic', 'czechia'],
    'DNK': ['denmark', 'dnk'],
    'DJI': ['dji', 'djibouti'],
    'DMA': ['dma', 'dominica'],
    'DOM': ['dom', 'dominican republic'],
    'COD': ['cod', 'democratic republic of the congo', 'dr congo'],
    'ECU': ['ecu', 'ecuador'],
    'EGY': ['egy', 'egypt'],
    'SLV': ['el salvador', 'slv'],
    'GNQ': ['equatorial guinea', 'gnq'],
    'ERI': ['eri', 'eritrea'],
    'EST': ['est', 'estonia'],
    'SWZ': ['eswatini', 'swaziland', 'swz'],
    'ETH': ['eth', 'ethiopia'],
    'FJI': ['fiji', 'fji'],
    'FIN': ['fin', 'finland'],
    'FRA': ['fra', 'france'],
    'GAB': ['gab', 'gabon'],
    'GMB': ['gambia', 'gmb'],
    'GEO': ['geo', 'georgia'],
    'DEU': ['deu', 'germany'],
    'GHA': ['gha', 'ghana'],
    'GRC': ['grc', 'greece'],
    'GRD': ['grd', 'grenada'],
    'GTM': ['gtm', 'guatemala'],
    'GIN': ['gin', 'guinea'],
    'GNB': ['gnb', 'guinea-bissau'],
    'GUY': ['guy', 'guyana'],
    'HTI': ['haiti', 'hti'],
    'HND': ['hnd', 'honduras'],
    'HUN': ['hun', 'hungary'],
    'HKG': ['hkg', 'hong kong'],
    'ISL': ['iceland', 'isl'],
    'IND': ['ind', 'india'],
    'IDN': ['idn', 'indonesia'],
    'IRN': ['iran', 'irn'],
    'IRQ': ['iraq', 'irq'],
    'IRL': ['ireland', 'irl'],
    'ISR': ['isr', 'israel'],
    'ITA': ['ita', 'italy'],
    'CIV': ['civ', 'cote d\'ivoire', 'côte d\'ivoire', 'ivory coast'],
    'JAM': ['jam', 'jamaica'],
    'JPN': ['japan', 'jpn'],
    'JOR': ['jor', 'jordan'],
    'KAZ': ['kaz', 'kazakhstan'],
    'KEN': ['ken', 'kenya'],
    'KIR': ['kir', 'kiribati'],
    'KWT': ['kuwait', 'kwt'],
    'KGZ': ['kgz', 'kyrgyzstan'],
    'LAO': ['lao', 'lao pdr', 'lao people\'s democratic republic', 'laos'],
    'LVA': ['latvia', 'lva'],
    'LBN': ['lbn', 'lebanon'],
    'LSO': ['lesotho', 'lso'],
    'LBR': ['lbr', 'liberia'],
    'LBY': ['lby', 'libya'],
    'LIE': ['lie', 'liechtenstein'],
    'LTU': ['lithuania', 'ltu'],
    'LUX': ['lux', 'luxembourg'],
    'MDG': ['madagascar', 'mdg'],
    'MWI': ['malawi', 'mwi'],
    'MYS': ['malaysia', 'mys'],
    'MDV': ['maldives', 'mdv'],
    'MLI': ['mali', 'mli'],
    'MLT': ['malta', 'mlt'],
    'MHL': ['marshall islands', 'mhl'],
    'MRT': ['mauritania', 'mrt'],
    'MUS': ['mauritius', 'mus'],
    'MEX': ['mex', 'mexico'],
    'FSM': ['fsm', 'micronesia'],
    'MDA': ['mda', 'moldova'],
    'MCO': ['mco', 'monaco'],
    'MNG': ['mng', 'mongolia'],
    'MNE': ['mne', 'montenegro'],
    'MAR': ['mar', 'morocco'],
    'MOZ': ['moz', 'mozambique'],
    'MMR': ['burma', 'mmr', 'myanmar'],
    'MAC': ['mac', 'macau'],
    'NAM': ['nam', 'namibia'],
    'NRU': ['nauru', 'nru'],
    'NPL': ['nepal', 'npl'],
    'NLD': ['netherlands', 'nld'],
    'NZL': ['new zealand', 'nzl'],
    'NIC': ['nic', 'nicaragua'],
    'NER': ['ner', 'niger'],
    'NGA': ['nga', 'nigeria'],
    'PRK': ['north korea', 'prk'],
    'MKD': ['macedonia', 'mkd', 'north macedonia'],
    'NOR': ['nor', 'norway'],
    'OMN': ['oman', 'omn'],
    'PAK': ['pak', 'pakistan'],
    'PLW': ['palau', 'plw'],
    'PSE': ['palestine', 'pse'],
    'PAN': ['pan', 'panama'],
    'PNG': ['papua new guinea', 'png'],
    'PRY': ['paraguay', 'pry'],
    'PER': ['per', 'peru', 'perú'],
    'PHL': ['philippines', 'phl'],
    'POL': ['pol', 'poland'],
    'PRT': ['portugal', 'prt'],
    'PRI': ['pri', 'puerto rico'],
    'QAT': ['qat', 'qatar'],
    'ROU': ['romania', 'rou'],
    'RUS': ['rus', 'russia', 'russian federation'],
    'RWA': ['rwa', 'rwanda'],
    'REU': ['reu', 'réunion'],
    'KNA': ['kna', 'saint kitts and nevis'],
    'LCA': ['lca', 'saint lucia'],
    'VCT': ['saint vincent and the grenadines', 'vct'],
    'WSM': ['samoa', 'wsm'],
    'SMR': ['san marino', 'smr'],
    'STP': ['sao tome and principe', 'stp'],
    'SAU': ['sau', 'saudi arabia'],
    'SEN': ['sen', 'senegal'],
    'SRB': ['serbia', 'srb'],
    'SYC': ['seychelles', 'syc'],
    'SLE': ['sierra leone', 'sle'],
    'SGP': ['sgp', 'singapore'],
    'SVK': ['slovakia', 'svk'],
    'SVN': ['slovenia', 'svn'],
    'SLB': ['slb', 'solomon islands'],
    'SOM': ['som', 'somalia'],
    'ZAF': ['south africa', 'zaf'],
    'KOR': ['kor', 'republic of korea', 'south korea'],
    'SSD': ['south sudan', 'ssd'],
    'ESP': ['esp', 'spain'],
    'LKA': ['lka', 'sri lanka'],
    'SDN': ['sdn', 'sudan'],
    'SUR': ['sur', 'suriname'],
    'SWE': ['swe', 'sweden'],
    'CHE': ['che', 'switzerland'],
    'SYR': ['syr', 'syria', 'syrian arab republic'],
    'TWN': ['taiwan', 'twn'],
    'TJK': ['tajikistan', 'tjk'],
    'TZA': ['tanzania', 'tza', 'united republic of tanzania'],
    'THA': ['tha', 'thailand'],
    'TLS': ['east timor', 'timor-leste', 'tls'],
    'TGO': ['tgo', 'togo'],
    'TON': ['ton', 'tonga'],
    'TTO': ['trinidad and tobago', 'tto'],
    'TUN': ['tun', 'tunisia'],
    'TUR': ['tur', 'turkey', 'türkiye'],
    'TKM': ['tkm', 'turkmenistan'],
    'TUV': ['tuv', 'tuvalu'],
    'UGA': ['uga', 'uganda'],
    'UKR': ['ukr', 'ukraine'],
    'ARE': ['are', 'uae', 'united arab emirates'],
    'GBR': ['gbr', 'united kingdom'],
    'USA': ['united states', 'united states of america', 'usa'],
    'URY': ['uruguay', 'ury'],
    'UZB': ['uzb', 'uzbekistan'],
    'VUT': ['vanuatu', 'vut'],
    'VAT': ['vat', 'vatican city'],
    'VEN': ['ven', 'venezuela'],
    'VNM': ['viet nam', 'vietnam', 'vnm'],
    'YEM': ['yem', 'yemen'],
    'ZMB': ['zambia', 'zmb'],
    'ZWE': ['zimbabwe', 'zwe'],
};
