name: Generate Documentation
on:
  workflow_dispatch:
  push:
    branches-ignore:
      - 'dependabot/**'
      - 'main'

jobs:
  runService:
    name: Run Service
    runs-on: guardian-linux-medium
    env:
      YARN_ENABLE_GLOBAL_CACHE: 'false'
    strategy:
      matrix:
        node-version: [ 20.20.2 ]
        mongodb-version: [ 7.0.21 ]
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - name: Checkout Code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: ${{ matrix.node-version }}

      - name: Enable Corepack
        run: corepack enable

      - name: Cache yarn
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: .yarn/cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install --immutable

      - name: Start NatsMQ
        uses: step-security/nats-action@2254b4cc4958120e36da3a096e8200dac968be1c # v0.1.4
        with:
          port: '4222'

      - name: Config Repo
        run: |
          git config --global user.name "envision-ci-agent"
          git config --global user.email "envision-ci-agent@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.DOC_UPDATE_API_KEY }}@github.com/$GITHUB_REPOSITORY
          git checkout "${GITHUB_REF:11}"

      - name: Start MongoDB
        uses: step-security/mongodb-github-action@4c2640417c3e31ebd7439e64d47f9751bd782772
        with:
          mongodb-version: ${{ matrix.mongodb-version }}

      - name: Build
        run: |
          pushd interfaces
          yarn run build
          popd
          pushd indexer-interfaces
          yarn run build
          popd
          pushd common
          yarn run build
          popd
          pushd indexer-common
          yarn run build
          popd
          pushd api-gateway
          yarn run build
          popd
          pushd indexer-api-gateway
          yarn run build
          popd
          pushd analytics-service
          yarn run build
          popd
        env:
          CI: true

      - name: Run service
        run: |
          pushd api-gateway
          yarn start &
          popd
          pushd indexer-api-gateway
          yarn start &
          popd
          pushd analytics-service
          yarn start &
          popd
          sleep 20
        env:
          QM_VERIFICATION: false

      - name: Download file
        run: |
          rm -fv swagger.yaml
          rm -fv swagger-indexer.yaml
          rm -fv swagger-analytics.yaml
          curl -o swagger.yaml http://127.0.0.1:3002/api-docs-yaml
          curl -o swagger-indexer.yaml http://127.0.0.1:3021/api-docs-yaml
          curl -o swagger-analytics.yaml http://127.0.0.1:3020/api-docs-yaml
          git add swagger.yaml
          git add swagger-indexer.yaml
          git add swagger-analytics.yaml
          git commit -m "[skip ci] Add swagger.yaml" && git push || exit 0