# SPDX-License-Identifier: Apache-2.0
name: "PR Formatting"
on:
  pull_request_target:
    types:
      - assigned
      - unassigned
      - labeled
      - unlabeled
      - opened
      - reopened
      - edited
      - converted_to_draft
      - ready_for_review
      - review_requested
      - review_request_removed
      - locked
      - unlocked
      - synchronize

defaults:
  run:
    shell: bash

permissions:
  statuses: write

jobs:
  title-check:
    name: Title Check
    runs-on: guardian-linux-medium
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.2
        with:
          egress-policy: audit

      - name: Check PR Title
        uses: step-security/conventional-pr-title-action@bb2263ec311ca158e9ffa6bd9b997fb425402034 # v3.2.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  assignee-check:
    name: Assignee Check
    runs-on: guardian-linux-medium

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.2
        with:
          egress-policy: audit

      - name: Check Assignee
        if: ${{ github.event.pull_request.assignees == null || github.event.pull_request.assignees[0] == null }}
        run: |
          echo "Assignee is not set. Failing the workflow."
          exit 1
