name: Guardian CI
on:
  workflow_dispatch:
  push:
    branches-ignore:
      - 'dependabot/**'
jobs:
  buildAndTest:
    name: Build and Test (Manual - Main)
    runs-on: guardian-linux-medium
    strategy:
      matrix:
        node-version: [ 20.20.2 ]
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - name: Checkout Code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e #v6.4.0
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup Yarn
        uses: Borales/actions-yarn@3766bb1335b98fb13c60eaf358fe20811b730a88 # v5.0.0
        with:
          cmd: --version

      - name: Locate yarn cache
        id: yarncache
        run: echo "dir=$(yarn cache dir)" >> "$GITHUB_OUTPUT"

      - name: Cache yarn
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: ${{ steps.yarncache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: |
          pushd interfaces
          yarn run build
          popd
          pushd common
          yarn run build
          popd
          pushd logger-service
          yarn run build
          popd
          pushd notification-service
          yarn run build
          popd
          pushd frontend
          npm install
          npm run build
          npm run build:prod
          npm run build:demo
          popd
          pushd auth-service
          yarn run build
          popd
          pushd policy-service
          yarn run build
          popd
          pushd guardian-service
          yarn run build
          popd
          pushd worker-service
          yarn run build
          popd
          pushd queue-service
          yarn run build
          popd
          pushd topic-listener-service
          yarn run build
          popd
          pushd api-gateway
          yarn run build
          popd
        env:
          CI: true
          NODE_OPTIONS: --openssl-legacy-provider

      - name: Detect secrets
        run: |
          yarn run detect-secrets
        env:
          CI: true
          NODE_OPTIONS: --openssl-legacy-provider

      - name: Lint
        run: |
          pushd interfaces
          npm run lint
          popd
          pushd common
          npm run lint
          popd
          pushd logger-service
          npm run lint
          popd
          pushd notification-service
          npm run lint
          popd
          pushd auth-service
          npm run lint
          popd
          pushd policy-service
          npm run lint
          popd
          pushd guardian-service
          npm run lint
          popd
          pushd worker-service
          npm run lint
          popd
          pushd queue-service
          npm run lint
          popd
          pushd topic-listener-service
          npm run lint
          popd
          pushd api-gateway
          npm run lint
          popd
        env:
          CI: true
          NODE_OPTIONS: --openssl-legacy-provider

      - name: Test
        run: |
          pushd common
          npm run test
          popd
          pushd policy-service
          npm run test
          popd
          pushd guardian-service
          npm run test
          popd
        env:
          CI: true
          NODE_OPTIONS: --openssl-legacy-provider
          OPERATOR_ID: ${{ secrets.CI_HEDERA_ACCOUNT }}
          OPERATOR_KEY: ${{ secrets.CI_HEDERA_PRIV_KEY }}

      - name: Publish Unit Test Results
        uses: step-security/publish-unit-test-result-action@681100d67b09305624c089873f12c545ee7cbc24 # v2.23.0
        if: always()
        with:
          files: test_results/**/*.xml
